# =====================================================================
# Supabase Configuration - Smart Divination Platform
# Ultra-Professional Supabase Local Development Setup
# =====================================================================

project_id = "smart-divination"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54325
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://smart-tarot.vercel.app", "https://smart-iching.vercel.app", "https://smart-runes.vercel.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

# Authentication providers
[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[auth.external.apple]
enabled = true
client_id = "env(APPLE_CLIENT_ID)"
secret = "env(APPLE_CLIENT_SECRET)"

[db]
port = 54322
shadow_port = 54323
major_version = 15

[realtime]
enabled = true
port = 54324
max_connections = 100

[studio]
enabled = true
port = 54326

[inbucket]
enabled = true
port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
buckets = [
  { name = "avatars", public = true },
  { name = "session-exports", public = false }
]

[edge_runtime]
enabled = true
port = 54329

[analytics]
enabled = false

[functions.smart-divination]
verify_jwt = true