name: smart_tarot
description: Smart Tarot — Flutter app migrated into canonical workspace
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.1
  supabase_flutter: ^2.1.0
  uuid: ^3.0.7
  common:
    path: ../../packages/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/app_icon/icon.png
  adaptive_icon_background: "#35173B"
  adaptive_icon_foreground: assets/app_icon/icon.png
