-- Migration: Seed Lunar Guide Templates
-- Created: 2025-11-15
-- Description: Populate base templates with astrologically accurate content
-- Source: Traditional lunar and elemental astrology

-- NEW MOON GUIDES (4 elements)

-- New Moon + Fire: Ignite Fresh Starts
INSERT INTO lunar_guide_templates (
  phase_id, element, priority,
  headline, tagline,
  focus_areas, energy_description, recommended_actions
) VALUES (
  'new_moon', 'fire', 1,
  '{"en": "Ignite Fresh Starts", "es": "Enciende Nuevos Comienzos", "ca": "Encén Nous Inicis"}',
  '{"en": "Seeds of courage planted in starlight", "es": "Semillas de coraje plantadas bajo las estrellas", "ca": "Llavors de coratge plantades sota les estrelles"}',
  '{"en": ["New intentions", "Bold action", "Courageous beginnings", "Passionate initiation"], "es": ["Nuevas intenciones", "Acción audaz", "Comienzos valientes", "Iniciación apasionada"], "ca": ["Noves intencions", "Acció audaç", "Començaments valents", "Iniciació apassionada"]}',
  '{"en": "Introspective potential meets fiery initiative. The new moon''s blank slate combines with fire''s passionate drive to create powerful momentum for brave new beginnings.", "es": "El potencial introspectivo se encuentra con la iniciativa ardiente. La página en blanco de la luna nueva se combina con el impulso apasionado del fuego para crear un poderoso impulso hacia nuevos comienzos valientes.", "ca": "El potencial introspectiu es troba amb la iniciativa ardent. La pàgina en blanc de la lluna nova es combina amb l''impuls apassionat del foc per crear un poderós impuls cap a nous començaments valents."}',
  '{"en": ["Set bold intentions for passionate projects", "Take the first courageous step toward a goal", "Light a candle and declare your vision", "Journal about what you want to courageously create"], "es": ["Establece intenciones audaces para proyectos apasionados", "Da el primer paso valiente hacia una meta", "Enciende una vela y declara tu visión", "Escribe sobre lo que quieres crear con valentía"], "ca": ["Estableix intencions audaces per a projectes apassionats", "Fes el primer pas valent cap a una fita", "Encén una espelma i declara la teva visió", "Escriu sobre el que vols crear amb valentia"]}'
);

-- New Moon + Earth: Ground New Foundations
INSERT INTO lunar_guide_templates (
  phase_id, element, priority,
  headline, tagline,
  focus_areas, energy_description, recommended_actions
) VALUES (
  'new_moon', 'earth', 1,
  '{"en": "Ground New Foundations", "es": "Establece Nuevas Bases", "ca": "Estableix Noves Bases"}',
  '{"en": "Practical seeds planted in fertile soil", "es": "Semillas prácticas plantadas en tierra fértil", "ca": "Llavors pràctiques plantades en terra fèrtil"}',
  '{"en": ["Practical intentions", "Material manifestation", "Grounded planning", "Tangible goals"], "es": ["Intenciones prácticas", "Manifestación material", "Planificación con los pies en la tierra", "Objetivos tangibles"], "ca": ["Intencions pràctiques", "Manifestació material", "Planificació amb els peus a terra", "Objectius tangibles"]}',
  '{"en": "Introspective potential meets practical foundation. The new moon''s fresh start energy combines with earth''s grounding nature to create stable, realistic plans that can truly manifest.", "es": "El potencial introspectivo se encuentra con la base práctica. La energía de nuevo comienzo de la luna nueva se combina con la naturaleza arraigadora de la tierra para crear planes estables y realistas que pueden manifestarse verdaderamente.", "ca": "El potencial introspectiu es troba amb la base pràctica. L''energia de nou començament de la lluna nova es combina amb la naturalesa arreladora de la terra per crear plans estables i realistes que poden manifestar-se veritablement."}',
  '{"en": ["Create a realistic action plan with concrete steps", "Set material goals (financial, physical health)", "Plant actual seeds or tend to plants", "Make a vision board with tangible images"], "es": ["Crea un plan de acción realista con pasos concretos", "Establece metas materiales (financieras, salud física)", "Planta semillas reales o cuida plantas", "Haz un tablero de visión con imágenes tangibles"], "ca": ["Crea un pla d''acció realista amb passos concrets", "Estableix objectius materials (financers, salut física)", "Planta llavors reals o cuida plantes", "Fes un tauler de visió amb imatges tangibles"]}'
);

-- New Moon + Air: Clarify New Ideas
INSERT INTO lunar_guide_templates (
  phase_id, element, priority,
  headline, tagline,
  focus_areas, energy_description, recommended_actions
) VALUES (
  'new_moon', 'air', 1,
  '{"en": "Clarify New Ideas", "es": "Clarifica Nuevas Ideas", "ca": "Clarifica Noves Idees"}',
  '{"en": "Fresh thoughts whispered on lunar winds", "es": "Pensamientos frescos susurrados en vientos lunares", "ca": "Pensaments frescos xiuxiuejats en vents lunars"}',
  '{"en": ["Mental clarity", "New perspectives", "Communication intentions", "Intellectual curiosity"], "es": ["Claridad mental", "Nuevas perspectivas", "Intenciones de comunicación", "Curiosidad intelectual"], "ca": ["Claredat mental", "Noves perspectives", "Intencions de comunicació", "Curiositat intel·lectual"]}',
  '{"en": "Introspective potential meets mental clarity. The new moon''s clean slate combines with air''s intellectual nature to birth fresh ideas and clear communication intentions.", "es": "El potencial introspectivo se encuentra con la claridad mental. La pizarra limpia de la luna nueva se combina con la naturaleza intelectual del aire para dar a luz ideas frescas e intenciones de comunicación claras.", "ca": "El potencial introspectiu es troba amb la claredat mental. La pissarra neta de la lluna nova es combina amb la naturalesa intel·lectual de l''aire per donar a llum idees fresques i intencions de comunicació clares."}',
  '{"en": ["Write down new ideas and concepts", "Set intentions for learning or communication", "Start a new course or study project", "Practice mindful breathing meditation"], "es": ["Escribe nuevas ideas y conceptos", "Establece intenciones de aprendizaje o comunicación", "Comienza un nuevo curso o proyecto de estudio", "Practica meditación consciente de respiración"], "ca": ["Escriu noves idees i conceptes", "Estableix intencions d''aprenentatge o comunicació", "Comença un nou curs o projecte d''estudi", "Practica meditació conscient de respiració"]}'
);

-- New Moon + Water: Dive Into Emotional Renewal
INSERT INTO lunar_guide_templates (
  phase_id, element, priority,
  headline, tagline,
  focus_areas, energy_description, recommended_actions
) VALUES (
  'new_moon', 'water', 1,
  '{"en": "Dive Into Emotional Renewal", "es": "Sumérgete en la Renovación Emocional", "ca": "Submergeix-te en la Renovació Emocional"}',
  '{"en": "Intuitive seeds planted in deep waters", "es": "Semillas intuitivas plantadas en aguas profundas", "ca": "Llavors intuïtives plantades en aigües profundes"}',
  '{"en": ["Emotional intentions", "Intuitive guidance", "Heart-centered goals", "Psychic renewal"], "es": ["Intenciones emocionales", "Guía intuitiva", "Objetivos centrados en el corazón", "Renovación psíquica"], "ca": ["Intencions emocionals", "Guia intuïtiva", "Objectius centrats en el cor", "Renovació psíquica"]}',
  '{"en": "Introspective potential meets emotional depth. The new moon''s retreat energy combines with water''s intuitive nature to create space for profound emotional intentions and psychic renewal.", "es": "El potencial introspectivo se encuentra con la profundidad emocional. La energía de retiro de la luna nueva se combina con la naturaleza intuitiva del agua para crear espacio para intenciones emocionales profundas y renovación psíquica.", "ca": "El potencial introspectiu es troba amb la profunditat emocional. L''energia de retir de la lluna nova es combina amb la naturalesa intuïtiva de l''aigua per crear espai per a intencions emocionals profundes i renovació psíquica."}',
  '{"en": ["Set emotional healing intentions", "Practice a water-based ritual (bath, ocean visit)", "Journal about feelings and intuitive guidance", "Meditate on what your heart truly desires"], "es": ["Establece intenciones de sanación emocional", "Practica un ritual basado en agua (baño, visita al océano)", "Escribe sobre sentimientos y guía intuitiva", "Medita sobre lo que tu corazón verdaderamente desea"], "ca": ["Estableix intencions de sanació emocional", "Practica un ritual basat en aigua (bany, visita a l''oceà)", "Escriu sobre sentiments i guia intuïtiva", "Medita sobre el que el teu cor veritablement desitja"]}'
);

-- WAXING CRESCENT GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('waxing_crescent', 'fire', 1,
 '{"en": "Fan the Flames of Momentum", "es": "Aviva las Llamas del Impulso", "ca": "Aviva les Flames de l''Impuls"}',
 '{"en": "First sparks of action ignite", "es": "Las primeras chispas de acción se encienden", "ca": "Les primeres espurnes d''acció s''encenen"}',
 '{"en": ["Building momentum", "Passionate action", "Creative energy", "Initiative"], "es": ["Construir impulso", "Acción apasionada", "Energía creativa", "Iniciativa"], "ca": ["Construir impuls", "Acció apassionada", "Energia creativa", "Iniciativa"]}',
 '{"en": "Emergent motivation meets fiery drive. The waxing crescent''s hope combines with fire''s enthusiasm to fuel the first bold actions toward your goals.", "es": "La motivación emergente se encuentra con el impulso ardiente. La esperanza de la luna creciente se combina con el entusiasmo del fuego para impulsar las primeras acciones audaces hacia tus objetivos.", "ca": "La motivació emergent es troba amb l''impuls ardent. L''esperança de la lluna creixent es combina amb l''entusiasme del foc per impulsar les primeres accions audaces cap als teus objectius."}',
 '{"en": ["Take action on your boldest intention", "Start that passionate project", "Exercise to build physical energy", "Create something with your hands"], "es": ["Actúa sobre tu intención más audaz", "Comienza ese proyecto apasionado", "Haz ejercicio para construir energía física", "Crea algo con tus manos"], "ca": ["Actua sobre la teva intenció més audaç", "Comença aquest projecte apassionat", "Fes exercici per construir energia física", "Crea alguna cosa amb les teves mans"]}'),

('waxing_crescent', 'earth', 1,
 '{"en": "Nurture Growing Foundations", "es": "Nutre las Bases en Crecimiento", "ca": "Nodreix les Bases en Creixement"}',
 '{"en": "Tender shoots break through rich earth", "es": "Brotes tiernos atraviesan tierra rica", "ca": "Brots tendres travessen terra rica"}',
 '{"en": ["Building foundations", "Practical steps", "Material progress", "Steady growth"], "es": ["Construir fundamentos", "Pasos prácticos", "Progreso material", "Crecimiento constante"], "ca": ["Construir fonaments", "Passos pràctics", "Progrés material", "Creixement constant"]}',
 '{"en": "Emergent growth meets practical action. The waxing crescent''s motivation combines with earth''s steady nature to build tangible foundations step by step.", "es": "El crecimiento emergente se encuentra con la acción práctica. La motivación de la luna creciente se combina con la naturaleza constante de la tierra para construir fundamentos tangibles paso a paso.", "ca": "El creixement emergent es troba amb l''acció pràctica. La motivació de la lluna creixent es combina amb la naturalesa constant de la terra per construir fonaments tangibles pas a pas."}',
 '{"en": ["Take one concrete step toward your goal", "Set up practical systems or structures", "Tend to your body or home", "Start a savings plan or budget"], "es": ["Da un paso concreto hacia tu objetivo", "Establece sistemas o estructuras prácticas", "Cuida tu cuerpo o hogar", "Comienza un plan de ahorros o presupuesto"], "ca": ["Fes un pas concret cap al teu objectiu", "Estableix sistemes o estructures pràctiques", "Cuida el teu cos o llar", "Comença un pla d''estalvis o pressupost"]}'),

('waxing_crescent', 'air', 1,
 '{"en": "Gather Information and Ideas", "es": "Recopila Información e Ideas", "ca": "Recopila Informació i Idees"}',
 '{"en": "Curious winds carry new knowledge", "es": "Vientos curiosos llevan nuevo conocimiento", "ca": "Vents curiosos porten nou coneixement"}',
 '{"en": ["Learning", "Research", "Communication", "Mental exploration"], "es": ["Aprendizaje", "Investigación", "Comunicación", "Exploración mental"], "ca": ["Aprenentatge", "Investigació", "Comunicació", "Exploració mental"]}',
 '{"en": "Emergent curiosity meets mental agility. The waxing crescent''s gathering phase combines with air''s intellectual nature to collect information and explore new concepts.", "es": "La curiosidad emergente se encuentra con la agilidad mental. La fase de recopilación de la luna creciente se combina con la naturaleza intelectual del aire para recopilar información y explorar nuevos conceptos.", "ca": "La curiositat emergent es troba amb l''agilitat mental. La fase de recol·lecció de la lluna creixent es combina amb la naturalesa intel·lectual de l''aire per recollir informació i explorar nous conceptes."}',
 '{"en": ["Research your goals or interests", "Have conversations about your plans", "Read or learn about your topic", "Network with like-minded people"], "es": ["Investiga tus objetivos o intereses", "Ten conversaciones sobre tus planes", "Lee o aprende sobre tu tema", "Conéctate con personas afines"], "ca": ["Investiga els teus objectius o interessos", "Tingues converses sobre els teus plans", "Llegeix o aprèn sobre el teu tema", "Connecta amb persones afins"]}'),

('waxing_crescent', 'water', 1,
 '{"en": "Trust Intuitive Guidance", "es": "Confía en la Guía Intuitiva", "ca": "Confia en la Guia Intuïtiva"}',
 '{"en": "Gentle waves guide the way forward", "es": "Olas suaves guían el camino hacia adelante", "ca": "Ones suaus guien el camí endavant"}',
 '{"en": ["Intuitive action", "Emotional guidance", "Psychic insights", "Heart wisdom"], "es": ["Acción intuitiva", "Guía emocional", "Percepciones psíquicas", "Sabiduría del corazón"], "ca": ["Acció intuïtiva", "Guia emocional", "Percepcions psíquiques", "Saviesa del cor"]}',
 '{"en": "Emergent hope meets emotional wisdom. The waxing crescent''s motivating energy combines with water''s intuitive flow to guide you by feeling and inner knowing.", "es": "La esperanza emergente se encuentra con la sabiduría emocional. La energía motivadora de la luna creciente se combina con el flujo intuitivo del agua para guiarte por el sentimiento y el conocimiento interior.", "ca": "L''esperança emergent es troba amb la saviesa emocional. L''energia motivadora de la lluna creixent es combina amb el flux intuïtiu de l''aigua per guiar-te pel sentiment i el coneixement interior."}',
 '{"en": ["Follow your gut feelings about next steps", "Practice divination or tarot", "Pay attention to dreams and symbols", "Trust emotional responses as guidance"], "es": ["Sigue tus corazonadas sobre los próximos pasos", "Practica la adivinación o el tarot", "Presta atención a sueños y símbolos", "Confía en las respuestas emocionales como guía"], "ca": ["Segueix les teves coraonades sobre els propers passos", "Practica l''endevinació o el tarot", "Presta atenció a somnis i símbols", "Confia en les respostes emocionals com a guia"]}');

-- FIRST QUARTER GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('first_quarter', 'fire', 1,
 '{"en": "Commit to Bold Action", "es": "Comprométete con Acción Audaz", "ca": "Compromet-te amb Acció Audaç"}',
 '{"en": "Decisive flames overcome resistance", "es": "Llamas decisivas superan la resistencia", "ca": "Flames decisives superen la resistència"}',
 '{"en": ["Decision point", "Overcoming obstacles", "Courageous commitment", "Breakthrough action"], "es": ["Punto de decisión", "Superar obstáculos", "Compromiso valiente", "Acción decisiva"], "ca": ["Punt de decisió", "Superar obstacles", "Compromís valent", "Acció decisiva"]}',
 '{"en": "Active decision-making meets passionate courage. The first quarter''s challenge point combines with fire''s bold nature to push through resistance and commit fully to your goals.", "es": "La toma de decisiones activa se encuentra con el coraje apasionado. El punto de desafío del primer cuarto se combina con la naturaleza audaz del fuego para superar la resistencia y comprometerse completamente con tus objetivos.", "ca": "La presa de decisions activa es troba amb el coratge apassionat. El punt de desafiament del primer quart es combina amb la naturalesa audaç del foc per superar la resistència i comprometre''s completament amb els teus objectius."}',
 '{"en": ["Make a decisive choice about your path", "Take bold action despite obstacles", "Push through resistance with courage", "Commit your energy fully to what matters"], "es": ["Toma una decisión decisiva sobre tu camino", "Toma acción audaz a pesar de los obstáculos", "Supera la resistencia con coraje", "Compromete tu energía completamente en lo que importa"], "ca": ["Pren una decisió decisiva sobre el teu camí", "Pren acció audaç malgrat els obstacles", "Supera la resistència amb coratge", "Compromet la teva energia completament en el que importa"]}'),

('first_quarter', 'earth', 1,
 '{"en": "Build Through Challenges", "es": "Construye a Través de Desafíos", "ca": "Construeix a Través de Desafiaments"}',
 '{"en": "Steady roots push through stone", "es": "Raíces firmes empujan a través de la piedra", "ca": "Arrels fermes empènyen a través de la pedra"}',
 '{"en": ["Practical decisions", "Structural adjustments", "Material commitment", "Persistent building"], "es": ["Decisiones prácticas", "Ajustes estructurales", "Compromiso material", "Construcción persistente"], "ca": ["Decisions pràctiques", "Ajustaments estructurals", "Compromís material", "Construcció persistent"]}',
 '{"en": "Active decision-making meets grounded persistence. The first quarter''s obstacle phase combines with earth''s steady nature to make practical adjustments and build stable structures despite challenges.", "es": "La toma de decisiones activa se encuentra con la persistencia arraigada. La fase de obstáculos del primer cuarto se combina con la naturaleza constante de la tierra para hacer ajustes prácticos y construir estructuras estables a pesar de los desafíos.", "ca": "La presa de decisions activa es troba amb la persistència arrelada. La fase d''obstacles del primer quart es combina amb la naturalesa constant de la terra per fer ajustaments pràctics i construir estructures estables malgrat els desafiaments."}',
 '{"en": ["Adjust your plan based on practical realities", "Make material commitments (sign contracts, invest)", "Work through physical obstacles step by step", "Build sustainable structures despite resistance"], "es": ["Ajusta tu plan según las realidades prácticas", "Haz compromisos materiales (firmar contratos, invertir)", "Trabaja a través de obstáculos físicos paso a paso", "Construye estructuras sostenibles a pesar de la resistencia"], "ca": ["Ajusta el teu pla segons les realitats pràctiques", "Fes compromisos materials (signar contractes, invertir)", "Treballa a través d''obstacles físics pas a pas", "Construeix estructures sostenibles malgrat la resistència"]}'),

('first_quarter', 'air', 1,
 '{"en": "Choose Your Direction", "es": "Elige Tu Dirección", "ca": "Tria la Teva Direcció"}',
 '{"en": "Clear winds reveal the path forward", "es": "Vientos claros revelan el camino adelante", "ca": "Vents clars revelen el camí endavant"}',
 '{"en": ["Mental clarity", "Communication choices", "Intellectual commitment", "Decisive thinking"], "es": ["Claridad mental", "Elecciones de comunicación", "Compromiso intelectual", "Pensamiento decisivo"], "ca": ["Claredat mental", "Eleccions de comunicació", "Compromís intel·lectual", "Pensament decisiu"]}',
 '{"en": "Active decision-making meets mental precision. The first quarter''s choice point combines with air''s clarity to cut through confusion and make clear intellectual commitments.", "es": "La toma de decisiones activa se encuentra con la precisión mental. El punto de elección del primer cuarto se combina con la claridad del aire para cortar la confusión y hacer compromisos intelectuales claros.", "ca": "La presa de decisions activa es troba amb la precisió mental. El punt d''elecció del primer quart es combina amb la claredat de l''aire per tallar la confusió i fer compromisos intel·lectuals clars."}',
 '{"en": ["Make a clear decision about communication or learning", "Have the important conversation you''ve been avoiding", "Commit to a course of study or intellectual pursuit", "Write out your decision and reasoning"], "es": ["Toma una decisión clara sobre comunicación o aprendizaje", "Ten la conversación importante que has estado evitando", "Comprométete con un curso de estudio o búsqueda intelectual", "Escribe tu decisión y razonamiento"], "ca": ["Pren una decisió clara sobre comunicació o aprenentatge", "Tingues la conversa important que has estat evitant", "Compromet-te amb un curs d''estudi o cerca intel·lectual", "Escriu la teva decisió i raonament"]}'),

('first_quarter', 'water', 1,
 '{"en": "Trust Emotional Conviction", "es": "Confía en la Convicción Emocional", "ca": "Confia en la Convicció Emocional"}',
 '{"en": "Deep currents carry certainty", "es": "Corrientes profundas llevan certeza", "ca": "Corrents profundes porten certesa"}',
 '{"en": ["Emotional clarity", "Heart decisions", "Intuitive commitment", "Feeling-based choices"], "es": ["Claridad emocional", "Decisiones del corazón", "Compromiso intuitivo", "Elecciones basadas en sentimientos"], "ca": ["Claredat emocional", "Decisions del cor", "Compromís intuïtiu", "Eleccions basades en sentiments"]}',
 '{"en": "Active decision-making meets emotional knowing. The first quarter''s challenge phase combines with water''s intuitive depth to make heart-centered commitments despite fears or doubts.", "es": "La toma de decisiones activa se encuentra con el conocimiento emocional. La fase de desafío del primer cuarto se combina con la profundidad intuitiva del agua para hacer compromisos centrados en el corazón a pesar de miedos o dudas.", "ca": "La presa de decisions activa es troba amb el coneixement emocional. La fase de desafiament del primer quart es combina amb la profunditat intuïtiva de l''aigua per fer compromisos centrats en el cor malgrat pors o dubtes."}',
 '{"en": ["Make a decision based on what your heart knows", "Commit to an emotional healing journey", "Trust your feelings over logic in this choice", "Release emotional resistance and choose love"], "es": ["Toma una decisión basada en lo que tu corazón sabe", "Comprométete con un viaje de sanación emocional", "Confía en tus sentimientos sobre la lógica en esta elección", "Libera la resistencia emocional y elige el amor"], "ca": ["Pren una decisió basada en el que el teu cor sap", "Compromet-te amb un viatge de sanació emocional", "Confia en els teus sentiments sobre la lògica en aquesta elecció", "Allibera la resistència emocional i tria l''amor"]}');

-- WAXING GIBBOUS GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('waxing_gibbous', 'fire', 1,
 '{"en": "Refine Your Passion", "es": "Refina Tu Pasión", "ca": "Refina la Teva Passió"}',
 '{"en": "Polish the spark into brilliant flame", "es": "Pule la chispa en llama brillante", "ca": "Poleix l''espurna en flama brillant"}',
 '{"en": ["Creative refinement", "Adjusting approach", "Perfecting expression", "Final preparations"], "es": ["Refinamiento creativo", "Ajustar enfoque", "Perfeccionar expresión", "Preparativos finales"], "ca": ["Refinament creatiu", "Ajustar enfocament", "Perfeccionar expressió", "Preparatius finals"]}',
 '{"en": "Refinement energy meets passionate precision. The waxing gibbous''s perfecting phase combines with fire''s creative force to polish your work and prepare for full manifestation.", "es": "La energía de refinamiento se encuentra con la precisión apasionada. La fase de perfeccionamiento de la luna gibosa creciente se combina con la fuerza creativa del fuego para pulir tu trabajo y prepararte para la manifestación completa.", "ca": "L''energia de refinament es troba amb la precisió apassionada. La fase de perfeccionament de la lluna gibosa creixent es combina amb la força creativa del foc per polir el teu treball i preparar-te per a la manifestació completa."}',
 '{"en": ["Review and improve your creative work", "Practice your presentation or performance", "Adjust your approach for maximum impact", "Prepare with passion for your moment"], "es": ["Revisa y mejora tu trabajo creativo", "Practica tu presentación o actuación", "Ajusta tu enfoque para máximo impacto", "Prepárate con pasión para tu momento"], "ca": ["Revisa i millora el teu treball creatiu", "Practica la teva presentació o actuació", "Ajusta el teu enfocament per màxim impacte", "Prepara''t amb passió per al teu moment"]}'),

('waxing_gibbous', 'earth', 1,
 '{"en": "Perfect the Details", "es": "Perfecciona los Detalles", "ca": "Perfecciona els Detalls"}',
 '{"en": "Fine-tune foundations before harvest", "es": "Ajusta finamente las bases antes de la cosecha", "ca": "Ajusta finament les bases abans de la collita"}',
 '{"en": ["Detail work", "Quality improvement", "Final adjustments", "Practical refinement"], "es": ["Trabajo de detalle", "Mejora de calidad", "Ajustes finales", "Refinamiento práctico"], "ca": ["Treball de detall", "Millora de qualitat", "Ajustaments finals", "Refinament pràctic"]}',
 '{"en": "Refinement energy meets practical precision. The waxing gibbous''s adjustment phase combines with earth''s attention to detail to perfect material work before completion.", "es": "La energía de refinamiento se encuentra con la precisión práctica. La fase de ajuste de la luna gibosa creciente se combina con la atención al detalle de la tierra para perfeccionar el trabajo material antes de la finalización.", "ca": "L''energia de refinament es troba amb la precisió pràctica. La fase d''ajustament de la lluna gibosa creixent es combina amb l''atenció al detall de la terra per perfeccionar el treball material abans de la finalització."}',
 '{"en": ["Review all practical details of your project", "Make final quality improvements", "Organize and refine your physical space", "Check financial calculations and logistics"], "es": ["Revisa todos los detalles prácticos de tu proyecto", "Haz mejoras finales de calidad", "Organiza y refina tu espacio físico", "Verifica cálculos financieros y logística"], "ca": ["Revisa tots els detalls pràctics del teu projecte", "Fes millores finals de qualitat", "Organitza i refina el teu espai físic", "Verifica càlculs financers i logística"]}'),

('waxing_gibbous', 'air', 1,
 '{"en": "Clarify Your Message", "es": "Clarifica Tu Mensaje", "ca": "Clarifica el Teu Missatge"}',
 '{"en": "Refine thoughts into crystal clarity", "es": "Refina pensamientos en claridad cristalina", "ca": "Refina pensaments en claredat cristal·lina"}',
 '{"en": ["Message refinement", "Communication polish", "Intellectual review", "Final edits"], "es": ["Refinamiento del mensaje", "Pulir comunicación", "Revisión intelectual", "Ediciones finales"], "ca": ["Refinament del missatge", "Polir comunicació", "Revisió intel·lectual", "Edicions finals"]}',
 '{"en": "Refinement energy meets mental clarity. The waxing gibbous''s perfecting phase combines with air''s precision to refine communication and polish intellectual work.", "es": "La energía de refinamiento se encuentra con la claridad mental. La fase de perfeccionamiento de la luna gibosa creciente se combina con la precisión del aire para refinar la comunicación y pulir el trabajo intelectual.", "ca": "L''energia de refinament es troba amb la claredat mental. La fase de perfeccionament de la lluna gibosa creixent es combina amb la precisió de l''aire per refinar la comunicació i polir el treball intel·lectual."}',
 '{"en": ["Edit and refine your writing or communication", "Practice your pitch or presentation", "Clarify your ideas with precision", "Get feedback and make final improvements"], "es": ["Edita y refina tu escritura o comunicación", "Practica tu presentación o propuesta", "Clarifica tus ideas con precisión", "Obtén retroalimentación y haz mejoras finales"], "ca": ["Edita i refina la teva escriptura o comunicació", "Practica la teva presentació o proposta", "Clarifica les teves idees amb precisió", "Obté retroalimentació i fes millores finals"]}'),

('waxing_gibbous', 'water', 1,
 '{"en": "Deepen Emotional Alignment", "es": "Profundiza la Alineación Emocional", "ca": "Aprofundeix l''Alineament Emocional"}',
 '{"en": "Adjust your flow to heart''s truth", "es": "Ajusta tu flujo a la verdad del corazón", "ca": "Ajusta el teu flux a la veritat del cor"}',
 '{"en": ["Emotional fine-tuning", "Heart alignment", "Intuitive refinement", "Feeling adjustments"], "es": ["Ajuste emocional fino", "Alineación del corazón", "Refinamiento intuitivo", "Ajustes de sentimientos"], "ca": ["Ajust emocional fi", "Alineament del cor", "Refinament intuïtiu", "Ajustaments de sentiments"]}',
 '{"en": "Refinement energy meets emotional depth. The waxing gibbous''s adjustment phase combines with water''s intuitive nature to ensure full alignment with your heart''s truth.", "es": "La energía de refinamiento se encuentra con la profundidad emocional. La fase de ajuste de la luna gibosa creciente se combina con la naturaleza intuitiva del agua para asegurar la alineación completa con la verdad de tu corazón.", "ca": "L''energia de refinament es troba amb la profunditat emocional. La fase d''ajustament de la lluna gibosa creixent es combina amb la naturalesa intuïtiva de l''aigua per assegurar l''alineament complet amb la veritat del teu cor."}',
 '{"en": ["Check if your path truly aligns with your heart", "Adjust your approach to feel more authentic", "Deepen your emotional connection to your goal", "Trust subtle feelings about final changes"], "es": ["Verifica si tu camino realmente se alinea con tu corazón", "Ajusta tu enfoque para sentirte más auténtico", "Profundiza tu conexión emocional con tu objetivo", "Confía en sentimientos sutiles sobre cambios finales"], "ca": ["Verifica si el teu camí realment s''alinea amb el teu cor", "Ajusta el teu enfocament per sentir-te més autèntic", "Aprofundeix la teva connexió emocional amb el teu objectiu", "Confia en sentiments subtils sobre canvis finals"]}');

-- FULL MOON GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('full_moon', 'fire', 1,
 '{"en": "Celebrate Your Victory", "es": "Celebra Tu Victoria", "ca": "Celebra la Teva Victòria"}',
 '{"en": "Brilliant blaze of achievement", "es": "Resplandor brillante de logro", "ca": "Resplandor brillant d''assoliment"}',
 '{"en": ["Creative culmination", "Passionate celebration", "Bold manifestation", "Victorious energy"], "es": ["Culminación creativa", "Celebración apasionada", "Manifestación audaz", "Energía victoriosa"], "ca": ["Culminació creativa", "Celebració apassionada", "Manifestació audaç", "Energia victoriosa"]}',
 '{"en": "Peak illumination meets fiery triumph. The full moon''s culmination combines with fire''s celebratory nature to honor achievements and burn away what no longer serves your passion.", "es": "La iluminación máxima se encuentra con el triunfo ardiente. La culminación de la luna llena se combina con la naturaleza celebratoria del fuego para honrar los logros y quemar lo que ya no sirve a tu pasión.", "ca": "La il·luminació màxima es troba amb el triomf ardent. La culminació de la lluna plena es combina amb la naturalesa celebratòria del foc per honorar els assoliments i cremar el que ja no serveix la teva passió."}',
 '{"en": ["Celebrate your creative achievements boldly", "Perform or share your work with confidence", "Release what dims your passionate fire", "Dance, move, express your victory"], "es": ["Celebra tus logros creativos audazmente", "Presenta o comparte tu trabajo con confianza", "Libera lo que apaga tu fuego apasionado", "Baila, muévete, expresa tu victoria"], "ca": ["Celebra els teus assoliments creatius audaçment", "Presenta o comparteix el teu treball amb confiança", "Allibera el que apaga el teu foc apassionat", "Balla, mou-te, expressa la teva victòria"]}'),

('full_moon', 'earth', 1,
 '{"en": "Harvest Your Results", "es": "Cosecha Tus Resultados", "ca": "Collita els Teus Resultats"}',
 '{"en": "Gather the fruits of your labor", "es": "Recoge los frutos de tu labor", "ca": "Recull els fruits del teu treball"}',
 '{"en": ["Material manifestation", "Tangible results", "Physical harvest", "Grounded celebration"], "es": ["Manifestación material", "Resultados tangibles", "Cosecha física", "Celebración arraigada"], "ca": ["Manifestació material", "Resultats tangibles", "Collita física", "Celebració arrelada"]}',
 '{"en": "Peak illumination meets earthly abundance. The full moon''s culmination combines with earth''s grounding to manifest tangible results and celebrate material achievements.", "es": "La iluminación máxima se encuentra con la abundancia terrenal. La culminación de la luna llena se combina con el arraigo de la tierra para manifestar resultados tangibles y celebrar logros materiales.", "ca": "La il·luminació màxima es troba amb l''abundància terrenal. La culminació de la lluna plena es combina amb l''arrelament de la terra per manifestar resultats tangibles i celebrar assoliments materials."}',
 '{"en": ["Acknowledge and receive your material results", "Complete transactions or finalize deals", "Enjoy the physical fruits of your work", "Release practical structures that limit growth"], "es": ["Reconoce y recibe tus resultados materiales", "Completa transacciones o finaliza acuerdos", "Disfruta los frutos físicos de tu trabajo", "Libera estructuras prácticas que limitan el crecimiento"], "ca": ["Reconeix i rep els teus resultats materials", "Completa transaccions o finalitza acords", "Gaudeix els fruits físics del teu treball", "Allibera estructures pràctiques que limiten el creixement"]}'),

('full_moon', 'air', 1,
 '{"en": "Illuminate Understanding", "es": "Ilumina el Entendimiento", "ca": "Il·lumina l''Enteniment"}',
 '{"en": "Clarity reaches its brilliant peak", "es": "La claridad alcanza su pico brillante", "ca": "La claredat arriba al seu pic brillant"}',
 '{"en": ["Mental clarity peak", "Intellectual revelation", "Communication culmination", "Truth illumination"], "es": ["Pico de claridad mental", "Revelación intelectual", "Culminación de comunicación", "Iluminación de verdad"], "ca": ["Pic de claredat mental", "Revelació intel·lectual", "Culminació de comunicació", "Il·luminació de veritat"]}',
 '{"en": "Peak illumination meets mental brilliance. The full moon''s clarity combines with air''s intellectual nature to reveal truths, complete communications, and release limiting beliefs.", "es": "La iluminación máxima se encuentra con la brillantez mental. La claridad de la luna llena se combina con la naturaleza intelectual del aire para revelar verdades, completar comunicaciones y liberar creencias limitantes.", "ca": "La il·luminació màxima es troba amb la brillantor mental. La claredat de la lluna plena es combina amb la naturalesa intel·lectual de l''aire per revelar veritats, completar comunicacions i alliberar creences limitants."}',
 '{"en": ["Share your ideas or publish your work", "Have revelatory conversations", "See situations with total clarity", "Release old beliefs that block your truth"], "es": ["Comparte tus ideas o publica tu trabajo", "Ten conversaciones reveladoras", "Ve situaciones con claridad total", "Libera viejas creencias que bloquean tu verdad"], "ca": ["Comparteix les teves idees o publica el teu treball", "Tingues converses reveladores", "Veu situacions amb claredat total", "Allibera velles creences que bloquegen la teva veritat"]}'),

('full_moon', 'water', 1,
 '{"en": "Feel It All Fully", "es": "Siéntelo Todo Completamente", "ca": "Sent-ho Tot Completament"}',
 '{"en": "Emotional tides reach fullness", "es": "Mareas emocionales alcanzan plenitud", "ca": "Marees emocionals arriben a la plenitud"}',
 '{"en": ["Emotional culmination", "Psychic peak", "Heart fullness", "Intuitive revelation"], "es": ["Culminación emocional", "Pico psíquico", "Plenitud del corazón", "Revelación intuitiva"], "ca": ["Culminació emocional", "Pic psíquic", "Plenitud del cor", "Revelació intuïtiva"]}',
 '{"en": "Peak illumination meets emotional depth. The full moon''s intensity combines with water''s feeling nature to bring profound emotional awareness and psychic clarity.", "es": "La iluminación máxima se encuentra con la profundidad emocional. La intensidad de la luna llena se combina con la naturaleza sentimental del agua para traer profunda conciencia emocional y claridad psíquica.", "ca": "La il·luminació màxima es troba amb la profunditat emocional. La intensitat de la lluna plena es combina amb la naturalesa sentimental de l''aigua per portar profunda consciència emocional i claredat psíquica."}',
 '{"en": ["Honor all your feelings without judgment", "Experience powerful emotional release", "Trust profound psychic insights tonight", "Let go of emotional patterns holding you back"], "es": ["Honra todos tus sentimientos sin juicio", "Experimenta liberación emocional poderosa", "Confía en percepciones psíquicas profundas esta noche", "Deja ir patrones emocionales que te detienen"], "ca": ["Honora tots els teus sentiments sense judici", "Experimenta alliberament emocional poderós", "Confia en percepcions psíquiques profundes aquesta nit", "Deixa anar patrons emocionals que t''aturen"]}');

-- WANING GIBBOUS GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('waning_gibbous', 'fire', 1,
 '{"en": "Share Your Light", "es": "Comparte Tu Luz", "ca": "Comparteix la Teva Llum"}',
 '{"en": "Pass the torch with generous flame", "es": "Pasa la antorcha con llama generosa", "ca": "Passa la torxa amb flama generosa"}',
 '{"en": ["Generous sharing", "Teaching passion", "Inspiring others", "Creative gratitude"], "es": ["Compartir generoso", "Enseñar pasión", "Inspirar a otros", "Gratitud creativa"], "ca": ["Compartir generós", "Ensenyar passió", "Inspirar altres", "Gratitud creativa"]}',
 '{"en": "Reflective generosity meets passionate wisdom. The waning gibbous''s sharing phase combines with fire''s inspirational nature to teach, motivate, and give thanks for creative blessings.", "es": "La generosidad reflexiva se encuentra con la sabiduría apasionada. La fase de compartir de la luna gibosa menguante se combina con la naturaleza inspiradora del fuego para enseñar, motivar y dar gracias por las bendiciones creativas.", "ca": "La generositat reflexiva es troba amb la saviesa apassionada. La fase de compartir de la lluna gibosa minvant es combina amb la naturalesa inspiradora del foc per ensenyar, motivar i donar gràcies per les benediccions creatives."}',
 '{"en": ["Teach what you''ve learned to others", "Share your creative process generously", "Express gratitude for your achievements", "Inspire someone with your passion"], "es": ["Enseña lo que has aprendido a otros", "Comparte tu proceso creativo generosamente", "Expresa gratitud por tus logros", "Inspira a alguien con tu pasión"], "ca": ["Ensenya el que has après a altres", "Comparteix el teu procés creatiu generosament", "Expressa gratitud pels teus assoliments", "Inspira algú amb la teva passió"]}'),

('waning_gibbous', 'earth', 1,
 '{"en": "Appreciate the Harvest", "es": "Aprecia la Cosecha", "ca": "Aprecia la Collita"}',
 '{"en": "Give thanks for material abundance", "es": "Da gracias por la abundancia material", "ca": "Dóna gràcies per l''abundància material"}',
 '{"en": ["Material gratitude", "Sharing resources", "Practical wisdom", "Grounded generosity"], "es": ["Gratitud material", "Compartir recursos", "Sabiduría práctica", "Generosidad arraigada"], "ca": ["Gratitud material", "Compartir recursos", "Saviesa pràctica", "Generositat arrelada"]}',
 '{"en": "Reflective generosity meets practical wisdom. The waning gibbous''s gratitude phase combines with earth''s abundance to share resources and appreciate material blessings.", "es": "La generosidad reflexiva se encuentra con la sabiduría práctica. La fase de gratitud de la luna gibosa menguante se combina con la abundancia de la tierra para compartir recursos y apreciar bendiciones materiales.", "ca": "La generositat reflexiva es troba amb la saviesa pràctica. La fase de gratitud de la lluna gibosa minvant es combina amb l''abundància de la terra per compartir recursos i apreciar benediccions materials."}',
 '{"en": ["Give thanks for your material blessings", "Share resources with those in need", "Teach practical skills you''ve mastered", "Appreciate your body and physical world"], "es": ["Da gracias por tus bendiciones materiales", "Comparte recursos con los necesitados", "Enseña habilidades prácticas que dominas", "Aprecia tu cuerpo y el mundo físico"], "ca": ["Dóna gràcies per les teves benediccions materials", "Comparteix recursos amb els necessitats", "Ensenya habilitats pràctiques que domines", "Aprecia el teu cos i el món físic"]}'),

('waning_gibbous', 'air', 1,
 '{"en": "Disseminate Knowledge", "es": "Difunde el Conocimiento", "ca": "Difon el Coneixement"}',
 '{"en": "Scatter seeds of wisdom on the winds", "es": "Esparce semillas de sabiduría en los vientos", "ca": "Escampa llavors de saviesa en els vents"}',
 '{"en": ["Sharing knowledge", "Teaching insights", "Grateful communication", "Intellectual generosity"], "es": ["Compartir conocimiento", "Enseñar percepciones", "Comunicación agradecida", "Generosidad intelectual"], "ca": ["Compartir coneixement", "Ensenyar percepcions", "Comunicació agraïda", "Generositat intel·lectual"]}',
 '{"en": "Reflective generosity meets mental clarity. The waning gibbous''s sharing phase combines with air''s communicative nature to teach, write, and express gratitude for insights gained.", "es": "La generosidad reflexiva se encuentra con la claridad mental. La fase de compartir de la luna gibosa menguante se combina con la naturaleza comunicativa del aire para enseñar, escribir y expresar gratitud por las percepciones obtenidas.", "ca": "La generositat reflexiva es troba amb la claredat mental. La fase de compartir de la lluna gibosa minvant es combina amb la naturalesa comunicativa de l''aire per ensenyar, escriure i expressar gratitud per les percepcions obtingudes."}',
 '{"en": ["Write about or teach what you''ve learned", "Have meaningful conversations to share insights", "Thank those who taught you", "Publish or present your knowledge"], "es": ["Escribe sobre o enseña lo que has aprendido", "Ten conversaciones significativas para compartir percepciones", "Agradece a quienes te enseñaron", "Publica o presenta tu conocimiento"], "ca": ["Escriu sobre o ensenya el que has après", "Tingues converses significatives per compartir percepcions", "Agraeix a qui t''ha ensenyat", "Publica o presenta el teu coneixement"]}'),

('waning_gibbous', 'water', 1,
 '{"en": "Overflow with Gratitude", "es": "Desborda de Gratitud", "ca": "Desborda de Gratitud"}',
 '{"en": "Heart overflows with thankful tears", "es": "El corazón desborda con lágrimas agradecidas", "ca": "El cor desborda amb llàgrimes agraïdes"}',
 '{"en": ["Emotional gratitude", "Healing sharing", "Compassionate wisdom", "Heart overflow"], "es": ["Gratitud emocional", "Compartir sanador", "Sabiduría compasiva", "Desbordamiento del corazón"], "ca": ["Gratitud emocional", "Compartir sanador", "Saviesa compassiva", "Desbordament del cor"]}',
 '{"en": "Reflective generosity meets emotional depth. The waning gibbous''s gratitude phase combines with water''s compassionate nature to share healing and express heartfelt thanks.", "es": "La generosidad reflexiva se encuentra con la profundidad emocional. La fase de gratitud de la luna gibosa menguante se combina con la naturaleza compasiva del agua para compartir sanación y expresar agradecimiento sincero.", "ca": "La generositat reflexiva es troba amb la profunditat emocional. La fase de gratitud de la lluna gibosa minvant es combina amb la naturalesa compassiva de l''aigua per compartir sanació i expressar agraïment sincer."}',
 '{"en": ["Express deep gratitude from your heart", "Share your emotional healing journey to help others", "Offer compassion and empathy generously", "Thank your intuition for guiding you"], "es": ["Expresa profunda gratitud desde tu corazón", "Comparte tu viaje de sanación emocional para ayudar a otros", "Ofrece compasión y empatía generosamente", "Agradece a tu intuición por guiarte"], "ca": ["Expressa profunda gratitud des del teu cor", "Comparteix el teu viatge de sanació emocional per ajudar altres", "Ofereix compassió i empatia generosament", "Agraeix a la teva intuïció per guiar-te"]}');

-- LAST QUARTER GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('last_quarter', 'fire', 1,
 '{"en": "Release Burnt Patterns", "es": "Libera Patrones Quemados", "ca": "Allibera Patrons Cremats"}',
 '{"en": "Let ashes fall to nourish new growth", "es": "Deja que las cenizas caigan para nutrir nuevo crecimiento", "ca": "Deixa que les cendres caiguin per nodrir nou creixement"}',
 '{"en": ["Letting go boldly", "Burning away excess", "Forgiving courageously", "Creative release"], "es": ["Dejar ir audazmente", "Quemar el exceso", "Perdonar valientemente", "Liberación creativa"], "ca": ["Deixar anar audaçment", "Cremar l''excés", "Perdonar valentament", "Alliberament creatiu"]}',
 '{"en": "Releasing energy meets passionate transformation. The last quarter''s cleansing phase combines with fire''s purifying nature to burn away what no longer serves your creative spirit.", "es": "La energía liberadora se encuentra con la transformación apasionada. La fase de limpieza del último cuarto se combina con la naturaleza purificadora del fuego para quemar lo que ya no sirve a tu espíritu creativo.", "ca": "L''energia alliberadora es troba amb la transformació apassionada. La fase de neteja de l''últim quart es combina amb la naturalesa purificadora del foc per cremar el que ja no serveix el teu esperit creatiu."}',
 '{"en": ["Burn (safely) something symbolic of what you release", "Forgive boldly and move forward", "Let go of creative projects that drain you", "Release anger through movement or expression"], "es": ["Quema (de forma segura) algo simbólico de lo que liberas", "Perdona audazmente y avanza", "Deja ir proyectos creativos que te agotan", "Libera la ira a través del movimiento o expresión"], "ca": ["Crema (de forma segura) alguna cosa simbòlica del que alliberes", "Perdona audaçment i avança", "Deixa anar projectes creatius que t''esgoten", "Allibera la ira a través del moviment o expressió"]}'),

('last_quarter', 'earth', 1,
 '{"en": "Clear Physical Space", "es": "Despeja Espacio Físico", "ca": "Neteja Espai Físic"}',
 '{"en": "Compost what served its purpose", "es": "Haz compost de lo que cumplió su propósito", "ca": "Fes compost del que va complir el seu propòsit"}',
 '{"en": ["Physical cleansing", "Material release", "Practical letting go", "Body detox"], "es": ["Limpieza física", "Liberación material", "Dejar ir práctico", "Desintoxicación corporal"], "ca": ["Neteja física", "Alliberament material", "Deixar anar pràctic", "Desintoxicació corporal"]}',
 '{"en": "Releasing energy meets practical cleansing. The last quarter''s purification phase combines with earth''s grounding to clear physical clutter and release material attachments.", "es": "La energía liberadora se encuentra con la limpieza práctica. La fase de purificación del último cuarto se combina con el arraigo de la tierra para limpiar el desorden físico y liberar apegos materiales.", "ca": "L''energia alliberadora es troba amb la neteja pràctica. La fase de purificació de l''últim quart es combina amb l''arrelament de la terra per netejar el desordre físic i alliberar apegaments materials."}',
 '{"en": ["Declutter your physical space", "Release material possessions you no longer need", "Cleanse your body (healthy detox, rest)", "Forgive material debts or resentments"], "es": ["Desordena tu espacio físico", "Libera posesiones materiales que ya no necesitas", "Limpia tu cuerpo (desintoxicación saludable, descanso)", "Perdona deudas materiales o resentimientos"], "ca": ["Desordena el teu espai físic", "Allibera possessions materials que ja no necessites", "Neteja el teu cos (desintoxicació saludable, descans)", "Perdona deutes materials o ressentiments"]}'),

('last_quarter', 'air', 1,
 '{"en": "Release Mental Burdens", "es": "Libera Cargas Mentales", "ca": "Allibera Càrregues Mentals"}',
 '{"en": "Let limiting thoughts drift away", "es": "Deja que pensamientos limitantes se alejen", "ca": "Deixa que pensaments limitants s''allunyin"}',
 '{"en": ["Mental cleansing", "Thought release", "Forgiving words", "Belief clearing"], "es": ["Limpieza mental", "Liberación de pensamientos", "Perdonar palabras", "Limpiar creencias"], "ca": ["Neteja mental", "Alliberament de pensaments", "Perdonar paraules", "Netejar creences"]}',
 '{"en": "Releasing energy meets mental clarity. The last quarter''s cleansing phase combines with air''s intellectual nature to release limiting beliefs and forgive harmful words.", "es": "La energía liberadora se encuentra con la claridad mental. La fase de limpieza del último cuarto se combina con la naturaleza intelectual del aire para liberar creencias limitantes y perdonar palabras dañinas.", "ca": "L''energia alliberadora es troba amb la claredat mental. La fase de neteja de l''últim quart es combina amb la naturalesa intel·lectual de l''aire per alliberar creences limitants i perdonar paraules danyines."}',
 '{"en": ["Write down and release limiting beliefs", "Forgive hurtful words spoken or received", "Clear mental clutter through meditation", "Let go of worry and overthinking"], "es": ["Escribe y libera creencias limitantes", "Perdona palabras hirientes dichas o recibidas", "Despeja el desorden mental a través de la meditación", "Deja ir la preocupación y el pensar demasiado"], "ca": ["Escriu i allibera creences limitants", "Perdona paraules feridores dites o rebudes", "Neteja el desordre mental a través de la meditació", "Deixa anar la preocupació i el pensar massa"]}'),

('last_quarter', 'water', 1,
 '{"en": "Cleanse Emotional Waters", "es": "Limpia Aguas Emocionales", "ca": "Neteja Aigües Emocionals"}',
 '{"en": "Let tears wash away old pain", "es": "Deja que las lágrimas laven el viejo dolor", "ca": "Deixa que les llàgrimes netegin el vell dolor"}',
 '{"en": ["Emotional release", "Heart cleansing", "Forgiveness", "Psychic purification"], "es": ["Liberación emocional", "Limpieza del corazón", "Perdón", "Purificación psíquica"], "ca": ["Alliberament emocional", "Neteja del cor", "Perdó", "Purificació psíquica"]}',
 '{"en": "Releasing energy meets emotional depth. The last quarter''s purification phase combines with water''s healing nature to cleanse emotional wounds and forgive from the heart.", "es": "La energía liberadora se encuentra con la profundidad emocional. La fase de purificación del último cuarto se combina con la naturaleza sanadora del agua para limpiar heridas emocionales y perdonar desde el corazón.", "ca": "L''energia alliberadora es troba amb la profunditat emocional. La fase de purificació de l''últim quart es combina amb la naturalesa sanadora de l''aigua per netejar ferides emocionals i perdonar des del cor."}',
 '{"en": ["Allow yourself to cry and release old pain", "Practice water rituals for emotional cleansing", "Forgive yourself and others from your heart", "Let go of emotional patterns that hurt you"], "es": ["Permítete llorar y liberar el viejo dolor", "Practica rituales de agua para limpieza emocional", "Perdónate a ti mismo y a otros desde tu corazón", "Deja ir patrones emocionales que te lastiman"], "ca": ["Permet-te plorar i alliberar el vell dolor", "Practica rituals d''aigua per neteja emocional", "Perdona''t a tu mateix i a altres des del teu cor", "Deixa anar patrons emocionals que et fan mal"]}');

-- WANING CRESCENT GUIDES (4 elements)

INSERT INTO lunar_guide_templates (phase_id, element, priority, headline, tagline, focus_areas, energy_description, recommended_actions) VALUES
('waning_crescent', 'fire', 1,
 '{"en": "Rest the Creative Flame", "es": "Descansa la Llama Creativa", "ca": "Descansa la Flama Creativa"}',
 '{"en": "Embers glow softly before rebirth", "es": "Las brasas brillan suavemente antes del renacimiento", "ca": "Les brases brillen suaument abans del renaixement"}',
 '{"en": ["Creative rest", "Gentle transformation", "Passion renewal", "Final closure"], "es": ["Descanso creativo", "Transformación gentil", "Renovación de pasión", "Cierre final"], "ca": ["Descans creatiu", "Transformació gentil", "Renovació de passió", "Tancament final"]}',
 '{"en": "Resting transformation meets creative renewal. The waning crescent''s quiet phase combines with fire''s regenerative spark to prepare passion for rebirth.", "es": "La transformación de descanso se encuentra con la renovación creativa. La fase tranquila de la luna menguante final se combina con la chispa regenerativa del fuego para preparar la pasión para el renacimiento.", "ca": "La transformació de descans es troba amb la renovació creativa. La fase tranquil·la de la lluna minvant final es combina amb l''espurna regenerativa del foc per preparar la passió per al renaixement."}',
 '{"en": ["Rest from creative output and productivity", "Journal about what you want to create next", "Close creative projects gently", "Nourish your passionate spirit with rest"], "es": ["Descansa de la producción creativa y productividad", "Escribe sobre lo que quieres crear después", "Cierra proyectos creativos suavemente", "Nutre tu espíritu apasionado con descanso"], "ca": ["Descansa de la producció creativa i productivitat", "Escriu sobre el que vols crear després", "Tanca projectes creatius suaument", "Nodreix el teu esperit apassionat amb descans"]}'),

('waning_crescent', 'earth', 1,
 '{"en": "Restore Your Body", "es": "Restaura Tu Cuerpo", "ca": "Restaura el Teu Cos"}',
 '{"en": "Fallow earth prepares for planting", "es": "Tierra en barbecho se prepara para plantar", "ca": "Terra en guaret es prepara per plantar"}',
 '{"en": ["Physical rest", "Body restoration", "Gentle closure", "Material renewal"], "es": ["Descanso físico", "Restauración del cuerpo", "Cierre gentil", "Renovación material"], "ca": ["Descans físic", "Restauració del cos", "Tancament gentil", "Renovació material"]}',
 '{"en": "Resting transformation meets physical restoration. The waning crescent''s recovery phase combines with earth''s regenerative nature to heal the body and complete practical cycles.", "es": "La transformación de descanso se encuentra con la restauración física. La fase de recuperación de la luna menguante final se combina con la naturaleza regenerativa de la tierra para sanar el cuerpo y completar ciclos prácticos.", "ca": "La transformació de descans es troba amb la restauració física. La fase de recuperació de la lluna minvant final es combina amb la naturalesa regenerativa de la terra per sanar el cos i completar cicles pràctics."}',
 '{"en": ["Prioritize sleep and physical rest", "Nourish your body with gentle care", "Finish practical loose ends", "Prepare your space for new beginnings"], "es": ["Prioriza el sueño y el descanso físico", "Nutre tu cuerpo con cuidado gentil", "Termina cabos sueltos prácticos", "Prepara tu espacio para nuevos comienzos"], "ca": ["Prioritza el son i el descans físic", "Nodreix el teu cos amb cura gentil", "Acaba caps solts pràctics", "Prepara el teu espai per nous començaments"]}'),

('waning_crescent', 'air', 1,
 '{"en": "Quiet the Mind", "es": "Calma la Mente", "ca": "Calma la Ment"}',
 '{"en": "Gentle winds carry whispers of rest", "es": "Vientos gentiles llevan susurros de descanso", "ca": "Vents gentils porten xiuxiueigs de descans"}',
 '{"en": ["Mental rest", "Thought quieting", "Gentle completion", "Mindful closure"], "es": ["Descanso mental", "Calmar pensamientos", "Finalización gentil", "Cierre consciente"], "ca": ["Descans mental", "Calmar pensaments", "Finalització gentil", "Tancament conscient"]}',
 '{"en": "Resting transformation meets mental stillness. The waning crescent''s quiet phase combines with air''s peaceful nature to rest the mind and complete communication cycles.", "es": "La transformación de descanso se encuentra con la quietud mental. La fase tranquila de la luna menguante final se combina con la naturaleza pacífica del aire para descansar la mente y completar ciclos de comunicación.", "ca": "La transformació de descans es troba amb la quietud mental. La fase tranquil·la de la lluna minvant final es combina amb la naturalesa pacífica de l''aire per descansar la ment i completar cicles de comunicació."}',
 '{"en": ["Practice mental stillness and meditation", "Take a break from consuming information", "Journal final thoughts before the new cycle", "Complete pending communications gently"], "es": ["Practica la quietud mental y meditación", "Toma un descanso de consumir información", "Escribe pensamientos finales antes del nuevo ciclo", "Completa comunicaciones pendientes suavemente"], "ca": ["Practica la quietud mental i meditació", "Pren un descans de consumir informació", "Escriu pensaments finals abans del nou cicle", "Completa comunicacions pendents suaument"]}'),

('waning_crescent', 'water', 1,
 '{"en": "Surrender to the Deep", "es": "Ríndete a lo Profundo", "ca": "Rendeix-te a lo Profund"}',
 '{"en": "Dark waters hold transformative peace", "es": "Aguas oscuras contienen paz transformadora", "ca": "Aigües fosques contenen pau transformadora"}',
 '{"en": ["Emotional rest", "Psychic renewal", "Heart surrender", "Deep healing"], "es": ["Descanso emocional", "Renovación psíquica", "Rendición del corazón", "Sanación profunda"], "ca": ["Descans emocional", "Renovació psíquica", "Rendició del cor", "Sanació profunda"]}',
 '{"en": "Resting transformation meets emotional depth. The waning crescent''s surrender phase combines with water''s mystical nature to access deep healing and spiritual renewal.", "es": "La transformación de descanso se encuentra con la profundidad emocional. La fase de rendición de la luna menguante final se combina con la naturaleza mística del agua para acceder a sanación profunda y renovación espiritual.", "ca": "La transformació de descans es troba amb la profunditat emocional. La fase de rendició de la lluna minvant final es combina amb la naturalesa mística de l''aigua per accedir a sanació profunda i renovació espiritual."}',
 '{"en": ["Allow deep emotional rest and surrender", "Trust the mysterious transformation happening", "Practice water-based self-care rituals", "Honor your need for psychic withdrawal"], "es": ["Permite descanso emocional profundo y rendición", "Confía en la transformación misteriosa que ocurre", "Practica rituales de autocuidado basados en agua", "Honra tu necesidad de retiro psíquico"], "ca": ["Permet descans emocional profund i rendició", "Confia en la transformació misteriosa que passa", "Practica rituals d''autocura basats en aigua", "Honora la teva necessitat de retir psíquic"]}')
