arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: common_strings.dart
output-class: CommonStrings
synthetic-package: false
nullable-getter: false
untranslated-messages-file: build/l10n_missing.txt
preferred-supported-locales: [en, es, ca]
