/// Basic spread information for display in learning screens
///
/// This is a lightweight model that contains just enough information
/// to display a spread card in lists without loading full spread data.
class SpreadBasicInfo {
  const SpreadBasicInfo({
    required this.id,
    required this.name,
    required this.nameCA,
    required this.nameES,
    required this.description,
    required this.descriptionCA,
    required this.descriptionES,
    required this.cardCount,
    required this.complexity,
    required this.category,
  });

  final String id;
  final String name;
  final String nameCA;
  final String nameES;
  final String description;
  final String descriptionCA;
  final String descriptionES;
  final int cardCount;
  final String complexity;
  final String category;

  /// Get localized name
  String getName(String locale) {
    switch (locale) {
      case 'ca':
        return nameCA;
      case 'es':
        return nameES;
      default:
        return name;
    }
  }

  /// Get localized description
  String getDescription(String locale) {
    switch (locale) {
      case 'ca':
        return descriptionCA;
      case 'es':
        return descriptionES;
      default:
        return description;
    }
  }

  /// Get complexity label
  String getComplexityLabel(String locale) {
    switch (complexity) {
      case 'simple':
      case 'beginner':
        switch (locale) {
          case 'ca':
            return 'Principiant';
          case 'es':
            return 'Principiante';
          default:
            return 'Beginner';
        }
      case 'moderate':
      case 'intermediate':
        switch (locale) {
          case 'ca':
            return 'Intermedi';
          case 'es':
            return 'Intermedio';
          default:
            return 'Intermediate';
        }
      case 'complex':
      case 'advanced':
        switch (locale) {
          case 'ca':
            return 'Avançat';
          case 'es':
            return 'Avanzado';
          default:
            return 'Advanced';
        }
      default:
        return complexity;
    }
  }
}

/// Complete spread basic information for all 101 spreads
/// Extracted from backend spreads.ts
/// Generated: 2025-11-20
const List<SpreadBasicInfo> ALL_SPREADS_BASIC_INFO = [
  SpreadBasicInfo(
    id: 'single',
    name: 'Single Card',
    nameCA: 'Una Carta',
    nameES: 'Una Carta',
    description: 'One card for quick daily guidance and direct answers',
    descriptionCA: 'Una carta per orientació diària ràpida i respostes directes',
    descriptionES: 'Una carta para orientación diaria rápida y respuestas directas',
    cardCount: 1,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'two_card',
    name: 'Two Card',
    nameCA: 'Dues Cartes',
    nameES: 'Dos Cartas',
    description: 'Decision-making spread for binary choices',
    descriptionCA: 'Tirada de decisió per a opcions binàries',
    descriptionES: 'Tirada de decisión para opciones binarias',
    cardCount: 2,
    complexity: 'simple',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'three_card',
    name: 'Three Card Spread',
    nameCA: 'Tirada de Tres Cartes',
    nameES: 'Tirada de Tres Cartas',
    description: 'Versatile spread for past, present, future insights',
    descriptionCA: 'Tirada versàtil per a passat, present i futur',
    descriptionES: 'Tirada versátil para pasado, presente y futuro',
    cardCount: 3,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'five_card_cross',
    name: 'Five Card Cross',
    nameCA: 'Creu de Cinc Cartes',
    nameES: 'Cruz de Cinco Cartas',
    description: 'Comprehensive cross layout with blocks and advice',
    descriptionCA: 'Disposició en creu completa amb bloquejos i consells',
    descriptionES: 'Disposición en cruz completa con bloqueos y consejos',
    cardCount: 5,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'relationship',
    name: 'Relationship',
    nameCA: 'Relació',
    nameES: 'Relación',
    description: 'Seven cards exploring relationship dynamics',
    descriptionCA: 'Set cartes explorant les dinàmiques de relació',
    descriptionES: 'Siete cartas explorando las dinámicas de relación',
    cardCount: 7,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'pyramid',
    name: 'Pyramid',
    nameCA: 'Piràmide',
    nameES: 'Pirámide',
    description: 'Six cards holistic pyramid layout',
    descriptionCA: 'Sis cartes en disposició piramidal holística',
    descriptionES: 'Seis cartas en disposición piramidal holística',
    cardCount: 6,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'horseshoe',
    name: 'Horseshoe',
    nameCA: 'Ferradura',
    nameES: 'Herradura',
    description: 'Seven card horseshoe for comprehensive guidance',
    descriptionCA: 'Set cartes en ferradura per orientació completa',
    descriptionES: 'Siete cartas en herradura para orientación completa',
    cardCount: 7,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'celtic_cross',
    name: 'Celtic Cross',
    nameCA: 'Creu Celta',
    nameES: 'Cruz Celta',
    description: 'Ten card master spread for complex situations',
    descriptionCA: 'Tirada mestra de deu cartes per situacions complexes',
    descriptionES: 'Tirada maestra de diez cartas para situaciones complejas',
    cardCount: 10,
    complexity: 'complex',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'star',
    name: 'Star',
    nameCA: 'Estrella',
    nameES: 'Estrella',
    description: 'Seven card star pattern for self-discovery',
    descriptionCA: 'Set cartes en estrella per a autoconeixement',
    descriptionES: 'Siete cartas en estrella para autoconocimiento',
    cardCount: 7,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'astrological',
    name: 'Astrological Houses',
    nameCA: 'Cases Astrològiques',
    nameES: 'Casas Astrológicas',
    description: 'Twelve cards representing the astrological houses',
    descriptionCA: 'Dotze cartes representant les cases astrològiques',
    descriptionES: 'Doce cartas representando las casas astrológicas',
    cardCount: 12,
    complexity: 'advanced',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'year_ahead',
    name: 'Year Ahead',
    nameCA: 'Any Endavant',
    nameES: 'Año Por Delante',
    description: 'Twelve cards for monthly forecast',
    descriptionCA: 'Dotze cartes per a pronòstic mensual',
    descriptionES: 'Doce cartas para pronóstico mensual',
    cardCount: 12,
    complexity: 'advanced',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'morning_guidance',
    name: 'Morning Guidance',
    nameCA: 'Orientació Matinal',
    nameES: 'Orientación Matutina',
    description: 'Three cards to set intentions for your day',
    descriptionCA: 'Tres cartes per establir intencions per al teu dia',
    descriptionES: 'Tres cartas para establecer intenciones para tu día',
    cardCount: 3,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'evening_reflection',
    name: 'Evening Reflection',
    nameCA: 'Reflexió Vespertina',
    nameES: 'Reflexión Vespertina',
    description: 'Three cards to reflect on your day and prepare for tomorrow',
    descriptionCA: 'Tres cartes per reflexionar sobre el teu dia i preparar-te per demà',
    descriptionES: 'Tres cartas para reflexionar sobre tu día y prepararte para mañana',
    cardCount: 3,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'weekly_overview',
    name: 'Weekly Overview',
    nameCA: 'Visió Setmanal',
    nameES: 'Visión Semanal',
    description: 'Seven cards, one for each day of the week',
    descriptionCA: 'Set cartes, una per cada dia de la setmana',
    descriptionES: 'Siete cartas, una para cada día de la semana',
    cardCount: 7,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'yes_no',
    name: 'Yes/No Spread',
    nameCA: 'Tirada Sí/No',
    nameES: 'Tirada Sí/No',
    description: 'One card for a direct yes or no answer',
    descriptionCA: 'Una carta per a una resposta directa sí o no',
    descriptionES: 'Una carta para una respuesta directa sí o no',
    cardCount: 1,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'quick_insight',
    name: 'Quick Insight',
    nameCA: 'Visió Ràpida',
    nameES: 'Visión Rápida',
    description: 'Two cards for situation and advice',
    descriptionCA: 'Dues cartes per situació i consell',
    descriptionES: 'Dos cartas para situación y consejo',
    cardCount: 2,
    complexity: 'simple',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'new_love_potential',
    name: 'New Love Potential',
    nameCA: 'Potencial d\\',
    nameES: 'Potencial de Amor Nuevo',
    description: 'Five cards to discover new love opportunities',
    descriptionCA: 'Cinc cartes per descobrir noves oportunitats d\\',
    descriptionES: 'Cinco cartas para descubrir nuevas oportunidades de amor',
    cardCount: 5,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'healing_breakup',
    name: 'Healing After Breakup',
    nameCA: 'Curació Després d\\',
    nameES: 'Sanación Después de una Ruptura',
    description: 'Five cards to heal and move forward after heartbreak',
    descriptionCA: 'Cinc cartes per curar-se i avançar després del desamor',
    descriptionES: 'Cinco cartas para sanar y avanzar después del desamor',
    cardCount: 5,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'soulmate_search',
    name: 'Soulmate Search',
    nameCA: 'Cerca de l\\',
    nameES: 'Búsqueda del Alma Gemela',
    description: 'Seven cards to guide you toward your soulmate',
    descriptionCA: 'Set cartes per guiar-te cap a la teva ànima bessona',
    descriptionES: 'Siete cartas para guiarte hacia tu alma gemela',
    cardCount: 7,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'compatibility_check',
    name: 'Compatibility Check',
    nameCA: 'Comprovació de Compatibilitat',
    nameES: 'Verificación de Compatibilidad',
    description: 'Eight cards to assess relationship compatibility',
    descriptionCA: 'Vuit cartes per avaluar la compatibilitat de la relació',
    descriptionES: 'Ocho cartas para evaluar la compatibilidad de la relación',
    cardCount: 8,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'marriage_decision',
    name: 'Marriage Decision',
    nameCA: 'Decisió de Matrimoni',
    nameES: 'Decisión de Matrimonio',
    description: 'Seven cards to explore commitment and marriage readiness',
    descriptionCA: 'Set cartes per explorar el compromís i la preparació per al matrimoni',
    descriptionES: 'Siete cartas para explorar el compromiso y la preparación para el matrimonio',
    cardCount: 7,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'dating_guidance',
    name: 'Dating Guidance',
    nameCA: 'Orientació per a Cites',
    nameES: 'Orientación para Citas',
    description: 'Four cards for navigating the dating world',
    descriptionCA: 'Quatre cartes per navegar el món de les cites',
    descriptionES: 'Cuatro cartas para navegar el mundo de las citas',
    cardCount: 4,
    complexity: 'simple',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'toxic_relationship',
    name: 'Toxic Relationship',
    nameCA: 'Relació Tòxica',
    nameES: 'Relación Tóxica',
    description: 'Six cards to understand and heal from toxic patterns',
    descriptionCA: 'Sis cartes per comprendre i curar patrons tòxics',
    descriptionES: 'Seis cartas para comprender y sanar patrones tóxicos',
    cardCount: 6,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'self_love_journey',
    name: 'Self-Love Journey',
    nameCA: 'Viatge d\\',
    nameES: 'Viaje de Amor Propio',
    description: 'Five cards to cultivate self-love and acceptance',
    descriptionCA: 'Cinc cartes per cultivar l\\',
    descriptionES: 'Cinco cartas para cultivar el amor propio y la aceptación',
    cardCount: 5,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'intimacy_issues',
    name: 'Intimacy Issues',
    nameCA: 'Problemes d\\',
    nameES: 'Problemas de Intimidad',
    description: 'Six cards to deepen intimacy and connection',
    descriptionCA: 'Sis cartes per aprofundir la intimitat i la connexió',
    descriptionES: 'Seis cartas para profundizar la intimidad y la conexión',
    cardCount: 6,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'partnership_balance',
    name: 'Partnership Balance',
    nameCA: 'Equilibri de la Parella',
    nameES: 'Equilibrio de la Pareja',
    description: 'Six cards to restore balance in your relationship',
    descriptionCA: 'Sis cartes per restaurar l\\',
    descriptionES: 'Seis cartas para restaurar el equilibrio en su relación',
    cardCount: 6,
    complexity: 'moderate',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'love_triangle',
    name: 'Love Triangle',
    nameCA: 'Triangle Amorós',
    nameES: 'Triángulo Amoroso',
    description: 'Nine cards to navigate complex love situations',
    descriptionCA: 'Nou cartes per navegar situacions amoroses complexes',
    descriptionES: 'Nueve cartas para navegar situaciones amorosas complejas',
    cardCount: 9,
    complexity: 'complex',
    category: 'love',
  ),
  SpreadBasicInfo(
    id: 'job_search',
    name: 'Job Search',
    nameCA: 'Cerca de Feina',
    nameES: 'Búsqueda de Empleo',
    description: 'Navigate your job search with clarity on your strengths and timing',
    descriptionCA: 'Navega la teva cerca de feina amb claredat sobre les teves fortaleses i el moment',
    descriptionES: 'Navega tu búsqueda de empleo con claridad sobre tus fortalezas y el momento',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'interview_prep',
    name: 'Interview Preparation',
    nameCA: 'Preparació per a Entrevista',
    nameES: 'Preparación para Entrevista',
    description: 'Get ready for your interview with insights on strengths and expectations',
    descriptionCA: 'Prepara\\',
    descriptionES: 'Prepárate para tu entrevista con perspectivas sobre fortalezas y expectativas',
    cardCount: 4,
    complexity: 'simple',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'promotion_path',
    name: 'Promotion Path',
    nameCA: 'Camí cap a la Promoció',
    nameES: 'Camino hacia la Promoción',
    description: 'Map your path to advancement with clarity on gaps and timing',
    descriptionCA: 'Mapeja el teu camí cap a l\\',
    descriptionES: 'Mapea tu camino hacia el avance con claridad sobre brechas y momento',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'career_change',
    name: 'Career Change',
    nameCA: 'Canvi de Carrera',
    nameES: 'Cambio de Carrera',
    description: 'Navigate a major career transition with insight into your calling and obstacles',
    descriptionCA: 'Navega una transició professional important amb perspectiva sobre la teva vocació i obstacles',
    descriptionES: 'Navega una transición profesional importante con perspectiva sobre tu vocación y obstáculos',
    cardCount: 7,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'work_conflicts',
    name: 'Work Conflicts',
    nameCA: 'Conflictes Laborals',
    nameES: 'Conflictos Laborales',
    description: 'Resolve workplace tensions with understanding of root causes and solutions',
    descriptionCA: 'Resol tensions laborals amb comprensió de causes arrel i solucions',
    descriptionES: 'Resuelve tensiones laborales con comprensión de causas raíz y soluciones',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'team_dynamics',
    name: 'Team Dynamics',
    nameCA: 'Dinàmiques d\\',
    nameES: 'Dinámicas de Equipo',
    description: 'Understand and improve your team relationships and collaboration',
    descriptionCA: 'Comprèn i millora les teves relacions d\\',
    descriptionES: 'Comprende y mejora tus relaciones de equipo y colaboración',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'entrepreneurship',
    name: 'Entrepreneurship',
    nameCA: 'Emprenedoria',
    nameES: 'Emprendimiento',
    description: 'Comprehensive guidance for starting your own business venture',
    descriptionCA: 'Orientació completa per iniciar el teu propi negoci',
    descriptionES: 'Orientación completa para iniciar tu propio negocio',
    cardCount: 8,
    complexity: 'complex',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'side_hustle',
    name: 'Side Hustle',
    nameCA: 'Projecte Secundari',
    nameES: 'Proyecto Secundario',
    description: 'Explore turning your passion into a profitable side business',
    descriptionCA: 'Explora com convertir la teva passió en un negoci secundari rendible',
    descriptionES: 'Explora cómo convertir tu pasión en un negocio secundario rentable',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'work_life_balance',
    name: 'Work-Life Balance',
    nameCA: 'Equilibri Vida-Treball',
    nameES: 'Equilibrio Vida-Trabajo',
    description: 'Find harmony between professional demands and personal wellbeing',
    descriptionCA: 'Troba l\\',
    descriptionES: 'Encuentra la armonía entre las demandas profesionales y el bienestar personal',
    cardCount: 7,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'career_purpose',
    name: 'Career Purpose',
    nameCA: 'Propòsit Professional',
    nameES: 'Propósito Profesional',
    description: 'Discover your true calling and align your career with your soul purpose',
    descriptionCA: 'Descobreix la teva veritable vocació i alinea la teva carrera amb el propòsit de la teva ànima',
    descriptionES: 'Descubre tu verdadera vocación y alinea tu carrera con el propósito de tu alma',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'negotiation_strategy',
    name: 'Negotiation Strategy',
    nameCA: 'Estratègia de Negociació',
    nameES: 'Estrategia de Negociación',
    description: 'Strategic guidance for salary negotiations and professional deals',
    descriptionCA: 'Orientació estratègica per a negociacions salarials i acords professionals',
    descriptionES: 'Orientación estratégica para negociaciones salariales y acuerdos profesionales',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'professional_growth',
    name: 'Professional Growth',
    nameCA: 'Creixement Professional',
    nameES: 'Crecimiento Profesional',
    description: 'Chart your path to mastery and professional development',
    descriptionCA: 'Traça el teu camí cap a la mestria i el desenvolupament professional',
    descriptionES: 'Traza tu camino hacia la maestría y el desarrollo profesional',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'financial_overview',
    name: 'Financial Overview',
    nameCA: 'Visió General Financera',
    nameES: 'Visión General Financiera',
    description: 'Comprehensive view of your current financial situation and opportunities',
    descriptionCA: 'Visió completa de la teva situació financera actual i oportunitats',
    descriptionES: 'Visión completa de tu situación financiera actual y oportunidades',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'investment_decision',
    name: 'Investment Decision',
    nameCA: 'Decisió d\\',
    nameES: 'Decisión de Inversión',
    description: 'Evaluate investment opportunities with insight into risks and potential',
    descriptionCA: 'Avalua oportunitats d\\',
    descriptionES: 'Evalúa oportunidades de inversión con perspectiva sobre riesgos y potencial',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'debt_management',
    name: 'Debt Management',
    nameCA: 'Gestió de Deute',
    nameES: 'Gestión de Deuda',
    description: 'Navigate your debt with clarity on causes and path to freedom',
    descriptionCA: 'Navega el teu deute amb claredat sobre causes i camí cap a la llibertat',
    descriptionES: 'Navega tu deuda con claridad sobre causas y camino hacia la libertad',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'salary_negotiation',
    name: 'Salary Negotiation',
    nameCA: 'Negociació Salarial',
    nameES: 'Negociación Salarial',
    description: 'Prepare for salary discussions with insight into value and approach',
    descriptionCA: 'Prepara\\',
    descriptionES: 'Prepárate para discusiones salariales con perspectiva sobre valor y enfoque',
    cardCount: 4,
    complexity: 'simple',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'abundance_mindset',
    name: 'Abundance Mindset',
    nameCA: 'Mentalitat d\\',
    nameES: 'Mentalidad de Abundancia',
    description: 'Transform your money mindset from scarcity to abundance',
    descriptionCA: 'Transforma la teva mentalitat monetària d\\',
    descriptionES: 'Transforma tu mentalidad monetaria de escasez a abundancia',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'business_finances',
    name: 'Business Finances',
    nameCA: 'Finances del Negoci',
    nameES: 'Finanzas del Negocio',
    description: 'Comprehensive financial guidance for your business venture',
    descriptionCA: 'Orientació financera completa per al teu negoci',
    descriptionES: 'Orientación financiera completa para tu negocio',
    cardCount: 7,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'savings_goals',
    name: 'Savings Goals',
    nameCA: 'Objectius d\\',
    nameES: 'Objetivos de Ahorro',
    description: 'Achieve your savings goals with clarity on obstacles and strategy',
    descriptionCA: 'Aconsegueix els teus objectius d\\',
    descriptionES: 'Logra tus objetivos de ahorro con claridad sobre obstáculos y estrategia',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'financial_blocks',
    name: 'Financial Blocks',
    nameCA: 'Bloquejos Financers',
    nameES: 'Bloqueos Financieros',
    description: 'Identify and release blocks preventing financial flow',
    descriptionCA: 'Identifica i allibera bloquejos que impedeixen el flux financer',
    descriptionES: 'Identifica y libera bloqueos que impiden el flujo financiero',
    cardCount: 6,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'money_flow',
    name: 'Money Flow',
    nameCA: 'Flux de Diners',
    nameES: 'Flujo de Dinero',
    description: 'Understand and improve the flow of money in your life',
    descriptionCA: 'Comprèn i millora el flux de diners a la teva vida',
    descriptionES: 'Comprende y mejora el flujo de dinero en tu vida',
    cardCount: 5,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'prosperity_path',
    name: 'Prosperity Path',
    nameCA: 'Camí cap a la Prosperitat',
    nameES: 'Camino hacia la Prosperidad',
    description: 'Map your journey to lasting prosperity and financial well-being',
    descriptionCA: 'Mapeja el teu viatge cap a la prosperitat duradora i el benestar financer',
    descriptionES: 'Mapea tu viaje hacia la prosperidad duradera y el bienestar financiero',
    cardCount: 7,
    complexity: 'moderate',
    category: 'career',
  ),
  SpreadBasicInfo(
    id: 'spiritual_path',
    name: 'Spiritual Path',
    nameCA: 'Camí Espiritual',
    nameES: 'Camino Espiritual',
    description: 'Seven card journey pattern revealing your spiritual ascension and growth',
    descriptionCA: 'Set cartes en patró de viatge que revelen la teva ascensió i creixement espiritual',
    descriptionES: 'Siete cartas en patrón de viaje que revelan tu ascensión y crecimiento espiritual',
    cardCount: 7,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'chakra_alignment',
    name: 'Chakra Alignment',
    nameCA: 'Alineació de Chakres',
    nameES: 'Alineación de Chakras',
    description: 'Seven card vertical layout examining each chakra from root to crown',
    descriptionCA: 'Set cartes en disposició vertical que examinen cada chakra des de l\\',
    descriptionES: 'Siete cartas en disposición vertical que examinan cada chakra desde la raíz hasta la corona',
    cardCount: 7,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'shadow_work',
    name: 'Shadow Work',
    nameCA: 'Treball de l\\',
    nameES: 'Trabajo de la Sombra',
    description: 'Six card circular pattern exploring hidden aspects and unconscious patterns',
    descriptionCA: 'Sis cartes en patró circular explorant aspectes ocults i patrons inconscients',
    descriptionES: 'Seis cartas en patrón circular explorando aspectos ocultos y patrones inconscientes',
    cardCount: 6,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'life_purpose',
    name: 'Life Purpose',
    nameCA: 'Propòsit de Vida',
    nameES: 'Propósito de Vida',
    description: 'Eight card star pattern revealing your soul mission and calling',
    descriptionCA: 'Vuit cartes en patró d\\',
    descriptionES: 'Ocho cartas en patrón de estrella revelando tu misión del alma y llamado',
    cardCount: 8,
    complexity: 'advanced',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'spiritual_awakening',
    name: 'Spiritual Awakening',
    nameCA: 'Despertar Espiritual',
    nameES: 'Despertar Espiritual',
    description: 'Seven card spiral pattern tracking your consciousness expansion journey',
    descriptionCA: 'Set cartes en patró espiral seguint el teu viatge d\\',
    descriptionES: 'Siete cartas en patrón espiral rastreando tu viaje de expansión de conciencia',
    cardCount: 7,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'past_life',
    name: 'Past Life',
    nameCA: 'Vida Passada',
    nameES: 'Vida Pasada',
    description: 'Six card horizontal timeline exploring karmic patterns and soul memories',
    descriptionCA: 'Sis cartes en línia temporal horitzontal explorant patrons kàrmics i memòries de l\\',
    descriptionES: 'Seis cartas en línea temporal horizontal explorando patrones kármicos y memorias del alma',
    cardCount: 6,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'spirit_guides',
    name: 'Spirit Guides',
    nameCA: 'Guies Espirituals',
    nameES: 'Guías Espirituales',
    description: 'Five card layout for connecting with spiritual guides and receiving messages',
    descriptionCA: 'Cinc cartes per connectar amb guies espirituals i rebre missatges',
    descriptionES: 'Cinco cartas para conectar con guías espirituales y recibir mensajes',
    cardCount: 5,
    complexity: 'simple',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'psychic_development',
    name: 'Psychic Development',
    nameCA: 'Desenvolupament Psíquic',
    nameES: 'Desarrollo Psíquico',
    description: 'Six card layout examining and strengthening intuitive abilities',
    descriptionCA: 'Sis cartes examinant i enfortint les habilitats intuïtives',
    descriptionES: 'Seis cartas examinando y fortaleciendo las habilidades intuitivas',
    cardCount: 6,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'full_moon_ritual',
    name: 'Full Moon Ritual',
    nameCA: 'Ritual de Lluna Plena',
    nameES: 'Ritual de Luna Llena',
    description: 'Five card lunar release spread for releasing what no longer serves',
    descriptionCA: 'Cinc cartes d\\',
    descriptionES: 'Cinco cartas de liberación lunar para soltar lo que ya no sirve',
    cardCount: 5,
    complexity: 'simple',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'new_moon_intentions',
    name: 'New Moon Intentions',
    nameCA: 'Intencions de Lluna Nova',
    nameES: 'Intenciones de Luna Nueva',
    description: 'Five card lunar manifestation spread for setting powerful intentions',
    descriptionCA: 'Cinc cartes de manifestació lunar per establir intencions poderoses',
    descriptionES: 'Cinco cartas de manifestación lunar para establecer intenciones poderosas',
    cardCount: 5,
    complexity: 'simple',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'meditation_journey',
    name: 'Meditation Journey',
    nameCA: 'Viatge de Meditació',
    nameES: 'Viaje de Meditación',
    description: 'Seven card inner path layout for deepening contemplative practice',
    descriptionCA: 'Set cartes del camí interior per aprofundir la pràctica contemplativa',
    descriptionES: 'Siete cartas del camino interior para profundizar la práctica contemplativa',
    cardCount: 7,
    complexity: 'moderate',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'sacred_calling',
    name: 'Sacred Calling',
    nameCA: 'Crida Sagrada',
    nameES: 'Llamado Sagrado',
    description: 'Eight card vocation pattern exploring spiritual work and divine service',
    descriptionCA: 'Vuit cartes en patró de vocació explorant el treball espiritual i el servei diví',
    descriptionES: 'Ocho cartas en patrón de vocación explorando el trabajo espiritual y el servicio divino',
    cardCount: 8,
    complexity: 'advanced',
    category: 'spiritual',
  ),
  SpreadBasicInfo(
    id: 'health_check',
    name: 'Health Check',
    nameCA: 'Control de Salut',
    nameES: 'Chequeo de Salud',
    description: 'Body, mind, and spirit wellness assessment',
    descriptionCA: 'Avaluació del benestar del cos, ment i esperit',
    descriptionES: 'Evaluación del bienestar del cuerpo, mente y espíritu',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'mental_health',
    name: 'Mental Health',
    nameCA: 'Salut Mental',
    nameES: 'Salud Mental',
    description: 'Deep exploration of mental and emotional wellness',
    descriptionCA: 'Exploració profunda del benestar mental i emocional',
    descriptionES: 'Exploración profunda del bienestar mental y emocional',
    cardCount: 6,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'energy_healing',
    name: 'Energy Healing',
    nameCA: 'Curació Energètica',
    nameES: 'Curación Energética',
    description: 'Chakra and energy flow alignment reading',
    descriptionCA: 'Lectura d\\',
    descriptionES: 'Lectura de alineación de chakras y flujo energético',
    cardCount: 7,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'stress_relief',
    name: 'Stress Relief',
    nameCA: 'Alleugeriment de l\\',
    nameES: 'Alivio del Estrés',
    description: 'Find peace and release tension from your life',
    descriptionCA: 'Troba pau i allibera la tensió de la teva vida',
    descriptionES: 'Encuentra paz y libera la tensión de tu vida',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'burnout_recovery',
    name: 'Burnout Recovery',
    nameCA: 'Recuperació de l\\',
    nameES: 'Recuperación del Agotamiento',
    description: 'Journey from exhaustion to renewed vitality',
    descriptionCA: 'Viatge de l\\',
    descriptionES: 'Viaje del agotamiento a la vitalidad renovada',
    cardCount: 6,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'body_wisdom',
    name: 'Body Wisdom',
    nameCA: 'Saviesa del Cos',
    nameES: 'Sabiduría del Cuerpo',
    description: 'Listen to your body\\',
    descriptionCA: 'Escolta els missatges i la intuïció del teu cos',
    descriptionES: 'Escucha los mensajes y la intuición de tu cuerpo',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'holistic_wellness',
    name: 'Holistic Wellness',
    nameCA: 'Benestar Holístic',
    nameES: 'Bienestar Holístico',
    description: 'Complete wellness across physical, mental, emotional, and spiritual dimensions',
    descriptionCA: 'Benestar complet en les dimensions física, mental, emocional i espiritual',
    descriptionES: 'Bienestar completo en las dimensiones física, mental, emocional y espiritual',
    cardCount: 8,
    complexity: 'complex',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'healing_journey',
    name: 'Healing Journey',
    nameCA: 'Viatge de Curació',
    nameES: 'Viaje de Sanación',
    description: 'Transform through the healing process from wound to wholeness',
    descriptionCA: 'Transforma\\',
    descriptionES: 'Transfórmate a través del proceso curativo desde la herida hasta la integridad',
    cardCount: 7,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'three_options',
    name: 'Three Options',
    nameCA: 'Tres Opcions',
    nameES: 'Tres Opciones',
    description: 'Deep analysis of three different paths or choices',
    descriptionCA: 'Anàlisi profunda de tres camins o opcions diferents',
    descriptionES: 'Análisis profundo de tres caminos u opciones diferentes',
    cardCount: 9,
    complexity: 'complex',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'opportunity_evaluation',
    name: 'Opportunity Evaluation',
    nameCA: 'Avaluació d\\',
    nameES: 'Evaluación de Oportunidad',
    description: 'Six cards to thoroughly evaluate an opportunity',
    descriptionCA: 'Sis cartes per avaluar a fons una oportunitat',
    descriptionES: 'Seis cartas para evaluar a fondo una oportunidad',
    cardCount: 6,
    complexity: 'moderate',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'risk_assessment',
    name: 'Risk Assessment',
    nameCA: 'Avaluació de Riscos',
    nameES: 'Evaluación de Riesgos',
    description: 'Five cards to weigh risk versus reward',
    descriptionCA: 'Cinc cartes per ponderar risc versus benefici',
    descriptionES: 'Cinco cartas para ponderar riesgo versus beneficio',
    cardCount: 5,
    complexity: 'moderate',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'timing_decision',
    name: 'Timing Decision',
    nameCA: 'Decisió de Moment',
    nameES: 'Decisión de Momento',
    description: 'Four cards to determine optimal timing',
    descriptionCA: 'Quatre cartes per determinar el moment òptim',
    descriptionES: 'Cuatro cartas para determinar el momento óptimo',
    cardCount: 4,
    complexity: 'simple',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'should_i',
    name: 'Should I',
    nameCA: 'Hauria de',
    nameES: 'Debería',
    description: 'Three cards for clear yes/no guidance with perspective',
    descriptionCA: 'Tres cartes per orientació clara sí/no amb perspectiva',
    descriptionES: 'Tres cartas para orientación clara sí/no con perspectiva',
    cardCount: 3,
    complexity: 'simple',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'life_crossroads',
    name: 'Life Crossroads',
    nameCA: 'Cruïlla de la Vida',
    nameES: 'Encrucijada de la Vida',
    description: 'Seven cards to navigate major life decisions',
    descriptionCA: 'Set cartes per navegar decisions importants de la vida',
    descriptionES: 'Siete cartas para navegar decisiones importantes de la vida',
    cardCount: 7,
    complexity: 'moderate',
    category: 'decision',
  ),
  SpreadBasicInfo(
    id: 'life_path',
    name: 'Life Path Journey',
    nameCA: 'Viatge del Camí de Vida',
    nameES: 'Viaje del Camino de Vida',
    description: 'Your innate essence and soul contract',
    descriptionCA: 'El Viatge del Boig aplicat al teu camí personal de desenvolupament',
    descriptionES: 'El Viaje del Loco aplicado a tu camino personal de desarrollo',
    cardCount: 7,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'hidden_talents',
    name: 'Hidden Talents',
    nameCA: 'Talents Ocults',
    nameES: 'Talentos Ocultos',
    description: 'Discover dormant abilities waiting to be awakened',
    descriptionCA: 'Descobreix habilitats dormides esperant ser despertades',
    descriptionES: 'Descubre habilidades dormidas esperando ser despertadas',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'psychological_blocks',
    name: 'Psychological Blocks',
    nameCA: 'Bloquejos Psicològics',
    nameES: 'Bloqueos Psicológicos',
    description: 'Shadow work spread to identify and release inner obstacles',
    descriptionCA: 'Tirada de treball d\\',
    descriptionES: 'Tirada de trabajo de sombra para identificar y liberar obstáculos interiores',
    cardCount: 6,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'behavior_patterns',
    name: 'Behavior Patterns',
    nameCA: 'Patrons de Comportament',
    nameES: 'Patrones de Comportamiento',
    description: 'Circular spread revealing repetitive cycles and how to break them',
    descriptionCA: 'Tirada circular revelant cicles repetitius i com trencar-los',
    descriptionES: 'Tirada circular revelando ciclos repetitivos y cómo romperlos',
    cardCount: 6,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'inner_child',
    name: 'Inner Child',
    nameCA: 'Infant Interior',
    nameES: 'Niño Interior',
    description: 'Jungian pentagon connecting with wounded and joyful aspects of self',
    descriptionCA: 'Pentàgon jungià connectant amb aspectes ferits i joiosos del jo',
    descriptionES: 'Pentágono junguiano conectando con aspectos heridos y gozosos del yo',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'shadow_self',
    name: 'Shadow Self',
    nameCA: 'El Jo Ombra',
    nameES: 'El Yo Sombra',
    description: 'Jungian shadow work exploring hidden aspects of self',
    descriptionCA: 'Treball de l\\',
    descriptionES: 'Trabajo de la sombra junguiana explorando aspectos ocultos del yo',
    cardCount: 6,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'authentic_self',
    name: 'Authentic Self',
    nameCA: 'El Jo Autèntic',
    nameES: 'El Yo Auténtico',
    description: 'Seven-card spiral discovering your true self beyond conditioning',
    descriptionCA: 'Espiral de set cartes descobrint el teu jo autèntic més enllà del condicionament',
    descriptionES: 'Espiral de siete cartas descubriendo tu yo auténtico más allá del condicionamiento',
    cardCount: 7,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'values_clarification',
    name: 'Values Clarification',
    nameCA: 'Clarificació de Valors',
    nameES: 'Clarificación de Valores',
    description: 'Five-card cross revealing your core values and alignment',
    descriptionCA: 'Creu de cinc cartes revelant els teus valors centrals i alineació',
    descriptionES: 'Cruz de cinco cartas revelando tus valores centrales y alineación',
    cardCount: 5,
    complexity: 'moderate',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'strengths_weaknesses',
    name: 'Strengths & Weaknesses',
    nameCA: 'Fortaleses i Debilitats',
    nameES: 'Fortalezas y Debilidades',
    description: 'Eight-card SWOT-style mandala for comprehensive self-assessment',
    descriptionCA: 'Mandala de vuit cartes estil DAFO per a autoavaluació integral',
    descriptionES: 'Mandala de ocho cartas estilo FODA para autoevaluación integral',
    cardCount: 8,
    complexity: 'complex',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'personal_identity',
    name: 'Personal Identity',
    nameCA: 'Identitat Personal',
    nameES: 'Identidad Personal',
    description: 'Nine-card grid exploring the multifaceted question: Who am I?',
    descriptionCA: 'Graella de nou cartes explorant la pregunta multifacètica: Qui sóc jo?',
    descriptionES: 'Cuadrícula de nueve cartas explorando la pregunta multifacética: ¿Quién soy yo?',
    cardCount: 9,
    complexity: 'complex',
    category: 'personal',
  ),
  SpreadBasicInfo(
    id: 'moving_relocation',
    name: 'Moving/Relocation',
    nameCA: 'Canvi de Domicili/Reubicació',
    nameES: 'Mudanza/Reubicación',
    description: 'Six cards exploring decision about changing homes or cities',
    descriptionCA: 'Sis cartes explorant la decisió de canviar de domicili o ciutats',
    descriptionES: 'Seis cartas explorando la decisión de cambiar de hogar o ciudades',
    cardCount: 6,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'travel_planning',
    name: 'Travel Planning',
    nameCA: 'Planificació de Viatge',
    nameES: 'Planificación de Viaje',
    description: 'Five cards providing guidance for upcoming journey',
    descriptionCA: 'Cinc cartes oferint orientació per al vostre futur viatge',
    descriptionES: 'Cinco cartas proporcionando orientación para su próximo viaje',
    cardCount: 5,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'legal_issues',
    name: 'Legal Issues',
    nameCA: 'Qüestions Legals',
    nameES: 'Asuntos Legales',
    description: 'Seven cards for understanding legal matters and justice',
    descriptionCA: 'Set cartes per entendre assumptes legals i justícia',
    descriptionES: 'Siete cartas para entender asuntos legales y justicia',
    cardCount: 7,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'family_dynamics',
    name: 'Family Dynamics',
    nameCA: 'Dinàmiques Familiars',
    nameES: 'Dinámicas Familiares',
    description: 'Eight cards for understanding family relationships and patterns',
    descriptionCA: 'Vuit cartes per entendre les relacions familiars i patrons',
    descriptionES: 'Ocho cartas para entender las relaciones familiares y patrones',
    cardCount: 8,
    complexity: 'complex',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'friendship',
    name: 'Friendship',
    nameCA: 'Amistat',
    nameES: 'Amistad',
    description: 'Six cards for understanding platonic relationships',
    descriptionCA: 'Sis cartes per entendre relacions platòniques',
    descriptionES: 'Seis cartas para entender relaciones platónicas',
    cardCount: 6,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'education_study',
    name: 'Education/Study',
    nameCA: 'Educació/Estudi',
    nameES: 'Educación/Estudio',
    description: 'Six cards providing guidance for learning and academic pursuits',
    descriptionCA: 'Sis cartes que ofereixen orientació per a l\\',
    descriptionES: 'Seis cartas que ofrecen orientación para el aprendizaje y las aspiraciones académicas',
    cardCount: 6,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'creative_project',
    name: 'Creative Project',
    nameCA: 'Projecte Creatiu',
    nameES: 'Proyecto Creativo',
    description: 'Seven cards exploring bringing creative visions to life',
    descriptionCA: 'Set cartes per explorar com dur visions creatives a la realitat',
    descriptionES: 'Siete cartas para explorar cómo llevar visiones creativas a la realidad',
    cardCount: 7,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'home_life',
    name: 'Home Life',
    nameCA: 'Vida en Casa',
    nameES: 'Vida en el Hogar',
    description: 'Six cards exploring domestic harmony and household matters',
    descriptionCA: 'Sis cartes que exploren l\\',
    descriptionES: 'Seis cartas que exploran la armonía doméstica y los asuntos del hogar',
    cardCount: 6,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'parenting',
    name: 'Parenting',
    nameCA: 'Paternitat',
    nameES: 'Paternidad',
    description: 'Eight cards offering guidance for raising children',
    descriptionCA: 'Vuit cartes que ofereixen orientació per a criar fills',
    descriptionES: 'Ocho cartas que ofrecen orientación para criar hijos',
    cardCount: 8,
    complexity: 'complex',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'major_life_change',
    name: 'Major Life Change',
    nameCA: 'Canvi Major de Vida',
    nameES: 'Cambio Mayor de Vida',
    description: 'Seven cards for navigating significant life transitions',
    descriptionCA: 'Set cartes per navegar transicions de vida significants',
    descriptionES: 'Siete cartas para navegar transiciones de vida significativas',
    cardCount: 7,
    complexity: 'moderate',
    category: 'general',
  ),
  SpreadBasicInfo(
    id: 'six_month_outlook',
    name: 'Six Month Outlook',
    nameCA: 'Perspectiva de Sis Mesos',
    nameES: 'Perspectiva de Seis Meses',
    description: 'Six month forecast exploring themes and milestones across two quarters',
    descriptionCA: 'Pronòstic de sis mesos explorant temes i fites en dos trimestres',
    descriptionES: 'Pronóstico de seis meses explorando temas e hitos en dos trimestres',
    cardCount: 6,
    complexity: 'moderate',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'quarterly_forecast',
    name: 'Quarterly Forecast',
    nameCA: 'Pronòstic Trimestral',
    nameES: 'Pronóstico Trimestral',
    description: 'Three month business cycle forecast aligned with seasonal rhythms',
    descriptionCA: 'Pronòstic de cicle de negoci de tres mesos alineat amb ritmes estacionals',
    descriptionES: 'Pronóstico de ciclo de negocios de tres meses alineado con ritmos estacionales',
    cardCount: 3,
    complexity: 'simple',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'monthly_forecast',
    name: 'Monthly Forecast',
    nameCA: 'Pronòstic Mensual',
    nameES: 'Pronóstico Mensual',
    description: 'Four card month ahead guidance with week-by-week flow',
    descriptionCA: 'Orientació del mes per davant amb flux setmanal a setmanal',
    descriptionES: 'Orientación del mes por delante con flujo semanal a semanal',
    cardCount: 4,
    complexity: 'simple',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'specific_event_timing',
    name: 'Specific Event Timing',
    nameCA: 'Moment d\\',
    nameES: 'Momento de un Evento Específico',
    description: 'Five card spread revealing when a specific event will unfold and what conditions surround it',
    descriptionCA: 'Tirada de cinc cartes que revela quan es desenvoluparà un esdeveniment específic i quines condicions l\\',
    descriptionES: 'Tirada de cinco cartas que revela cuándo se desarrollará un evento específico y qué condiciones lo rodean',
    cardCount: 5,
    complexity: 'moderate',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'four_seasons',
    name: 'Four Seasons',
    nameCA: 'Quatre Estacions',
    nameES: 'Cuatro Estaciones',
    description: 'Five card annual cycle exploring each season\\',
    descriptionCA: 'Tirada de cinc cartes del cicle anual que explora l\\',
    descriptionES: 'Tirada de cinco cartas del ciclo anual que explora la energía de cada estación y el tema general del año',
    cardCount: 5,
    complexity: 'moderate',
    category: 'timing',
  ),
  SpreadBasicInfo(
    id: 'next_steps_timeline',
    name: 'Next Steps Timeline',
    nameCA: 'Línia de Temps dels Propers Passos',
    nameES: 'Línea de Tiempo de los Próximos Pasos',
    description: 'Five card sequential action plan revealing immediate, short, medium, long-term steps and final outcome',
    descriptionCA: 'Tirada de cinc cartes que revela un pla d\\',
    descriptionES: 'Tirada de cinco cartas que revela un plan de acción secuencial con pasos inmediatos, cortos, medios, largos y resultado final',
    cardCount: 5,
    complexity: 'moderate',
    category: 'timing',
  ),
];

/// Get spread basic info by ID
SpreadBasicInfo? getSpreadBasicInfoById(String spreadId) {
  try {
    return ALL_SPREADS_BASIC_INFO.firstWhere(
      (spread) => spread.id == spreadId,
    );
  } catch (e) {
    return null;
  }
}

/// Get spreads for a list of IDs
List<SpreadBasicInfo> getSpreadsForIds(List<String> spreadIds) {
  return spreadIds
      .map((id) => getSpreadBasicInfoById(id))
      .whereType<SpreadBasicInfo>()
      .toList();
}
