# ULTRA-STRICT ANALYSIS - ZERO TOLERANCE FOR LOW QUALITY CODE
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - build/**
  
  language:
    strict-inference: true
    strict-raw-types: true
  
  errors:
    # Performance critical
    avoid_slow_async_io: error
    close_sinks: error
    
    # Type safety critical  
    always_specify_types: error
    type_annotate_public_apis: error
    avoid_dynamic_calls: error
    
    # Architecture compliance
    depend_on_referenced_packages: error
    implementation_imports: error
    
    # Code quality
    prefer_relative_imports: error
    sort_pub_dependencies: error

linter:
  rules:
    # ULTRA-STRICT TYPE SAFETY
    always_declare_return_types: true
    always_specify_types: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    
    # PERFORMANCE CRITICAL
    avoid_slow_async_io: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    
    # ARCHITECTURE ENFORCEMENT
    depend_on_referenced_packages: true
    implementation_imports: true
    prefer_relative_imports: true
    
    # CODE ORGANIZATION  
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    directives_ordering: true
    
    # ULTRA-CLEAN CODE
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_overrides: true
    
    # DOCUMENTATION ENFORCEMENT
    public_member_api_docs: true
    package_api_docs: true
    
    # SECURITY
    avoid_print: true