# Internationalization Configuration - Professional Multi-language Support
arb-dir: lib/shared/infrastructure/localization/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/shared/infrastructure/localization
preferred-supported-locales: 
  - en
  - es  
  - ca
nullable-getter: true
synthetic-package: false
header-file: lib/shared/infrastructure/localization/header.txt
untranslated-messages-file: lib/shared/infrastructure/localization/untranslated.json