name: smart_divination
description: Professional divination platform - unified engine for Tarot, I Ching & Runes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management - Type-safe DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Networking - Professional HTTP stack
  http: ^1.1.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Database - High performance local storage
  isar: ^3.1.8
  isar_flutter_libs: ^3.1.8
  path_provider: ^2.1.4
  
  # Crypto & Security - Verifiable randomness
  crypto: ^3.0.5
  uuid: ^4.5.1
  
  # UI & Animation - Professional experience
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Internationalization
  intl: ^0.19.0
  
  # Device Integration
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  
  # Storage & Preferences - Encrypted local data
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  
  # In-App Purchases - Multi-platform billing
  in_app_purchase: ^3.2.0
  
  # Utils
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
    
  # Code Generation - Professional toolchain
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.8
  
  # Testing - Comprehensive test suite
  mockito: ^5.4.4
  fake_async: ^1.3.1
  integration_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/packs/tarot/
    - assets/packs/iching/
    - assets/packs/runes/
    - assets/shared/
    - assets/lottie/
    
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700